### ISSUE TITLE
Crashes while creating a new word

### ISSUE THREAD

**Issue by filoe** [OctoAwesome/octoawesome#105]
Release 0.335 crashes while creating a new world:

> Anwendung: OctoClient.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.ArgumentOutOfRangeException
   bei System.Random.Next(Int32)
   bei OctoAwesome.Runtime.ResourceManager.GetPlanet(Int32)
   bei OctoAwesome.Runtime.ActorHost..ctor(OctoAwesome.Player)
   bei OctoAwesome.Runtime.Simulation.InsertPlayer(OctoAwesome.Player)
   bei OctoAwesome.Client.Components.PlayerComponent.InsertPlayer()
   bei OctoAwesome.Client.Screens.CreateUniverseScreen+<>c__DisplayClass4_0.<.ctor>b__2(MonoGameUi.Control, MonoGameUi.MouseEventArgs)
   bei MonoGameUi.Control.InternalLeftMouseClick(MonoGameUi.MouseEventArgs)
   bei MonoGameUi.Control.InternalLeftMouseClick(MonoGameUi.MouseEventArgs)
   bei MonoGameUi.Control.InternalLeftMouseClick(MonoGameUi.MouseEventArgs)
   bei MonoGameUi.Control.InternalLeftMouseClick(MonoGameUi.MouseEventArgs)
   bei MonoGameUi.Control.InternalLeftMouseClick(MonoGameUi.MouseEventArgs)
   bei MonoGameUi.Control.InternalLeftMouseClick(MonoGameUi.MouseEventArgs)
   bei MonoGameUi.BaseScreenComponent.Update(Microsoft.Xna.Framework.GameTime)
   bei Microsoft.Xna.Framework.Game+SortingFilteringCollection`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ForEachFilteredItem[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Action`2<System.__Canon,System.__Canon>, System.__Canon)
   bei Microsoft.Xna.Framework.Game.DoUpdate(Microsoft.Xna.Framework.GameTime)
   bei Microsoft.Xna.Framework.Game.Tick()
   bei MonoGame.Framework.WinFormsGameWindow.RunLoop()
   bei Microsoft.Xna.Framework.Game.Run(Microsoft.Xna.Framework.GameRunBehavior)
   bei OctoAwesome.Client.Program.Main()

**Comment by ManuelHu** [comment]
Extrem komisch. Im GitHub-Release kann ich's reproduzieren, im aus dem Sourcecode erstellten Programm (egal ob Debug oder Release) nicht.

@tomwendel Kannst du das Release einfach noch mal neu kompilieren und hochladen?

**Comment by tomwendel** [comment]
Das ist interessant...
Ich habe die Binaries neu erstellt und hochgeladen -> Selbes Problem. Das Problem wird (warum auch immer - das sollten wir mal noch rausfinden) vom Windows Security System verursacht. Dateien die aus dem Internet kommen werden mit gesonderten Rechten gestartet. Diese Einschränkung verursacht unser Problem.

Das lässt sich zwar einfach umgehen (In den ZIP-Eigenschaften vor dem Entpacken den Haken bei "Unblock" setzen), aber sollte natürlich nicht der Fall sein. Ich dachte zuerst, dass die App grundsätzlich keine Schreibrechte bekäme, stimmt aber so nicht. Ich untersuche das mal...

**Comment by ManuelHu** [comment]
Ich vermute, man kann diese Einschränkung nicht einfach umgehen (vielleicht mit einem Code Signing Certificate), sonst würde das ja jeder Virus machen. Wir sollten aber einen Hinweis einfügen, ich mach das gleich mal fürs Wiki. Dann kannst du die Issue ja schließen, das hat ja nichts mit OctoAwesome an sich zu tun.

**Comment by tomwendel** [comment]
Das komische ist, dass sie Ordner anlegen kann :D

**Comment by ManuelHu** [comment]
Ich schließe das mal, ich denke nicht, dass wir daran was ändern können.
