### ISSUE TITLE
Network Linux Server <--> Windows Client funktioniert nicht

### ISSUE THREAD

**Issue by ManuelHu** [OctoAwesome/octoawesome#111]
Wenn ich den Server auf meinem Raspberry laufen lasse und mich mit meinem Client von meinem Windows Rechner darauf verbinden will, bekomme ich am Client eine System.ServiceModel.CommunicationException:
```
Fehler beim Deserialisieren des Textkörpers der Antwortnachricht für Vorgang "Connect". Unerwartetes Dateiende gefunden. Folgende Elemente sind nicht abgeschlossen: Envelope.
```

Remote Stack Trace:
```
Server stack trace: 
   bei System.ServiceModel.Dispatcher.OperationFormatter.DeserializeReply(Message message, Object[] parameters)
   bei System.ServiceModel.Dispatcher.ProxyOperationRuntime.AfterReply(ProxyRpc& rpc)
   bei System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   bei System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   bei System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   bei System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
```

Wir sollten wirklich mal in den nächsten Streams das Thema Network ohne WCF angehen.

**Comment by tomwendel** [comment]
Mich würde viel eher die Ursache für die Fehlermeldung interessieren. BigEndian vs. LittleEndian wird vom Framework eigentlich weggekapselt.
Mal sehen was im nächsten Stream als nächstes Feature gewünscht wird. Laut Trello haben Sockets leider eher niedrige Prio. (6 Stimmen).

Von: Manuel Huber [mailto:notifications@github.com]
Gesendet: Sonntag, 20. März 2016 14:53
An: tomwendel/octoawesome
Betreff: [octoawesome] WCF Linux <--> Windows funktioniert nicht (#111)


Wenn ich den Server auf meinem Raspberry laufen lasse und mich mit meinem Client von meinem Windows Rechner darauf verbinden will, bekomme ich am Client eine System.ServiceModel.CommunicationException:

Fehler beim Deserialisieren des Textkörpers der Antwortnachricht für Vorgang "Connect". Unerwartetes Dateiende gefunden. Folgende Elemente sind nicht abgeschlossen: Envelope.

Remote Stack Trace:

Server stack trace:

   bei System.ServiceModel.Dispatcher.OperationFormatter.DeserializeReply(Message message, Object[] parameters)

   bei System.ServiceModel.Dispatcher.ProxyOperationRuntime.AfterReply(ProxyRpc& rpc)

   bei System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)

   bei System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)

   bei System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)

   bei System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)



Exception rethrown at [0]:

Wir sollten wirklich mal in den nächsten Streams das Thema Network ohne WCF angehen.

**Comment by CsharpLassi** [comment]
Hallo,
beim Raspberry müsst ihr immer etwas aufpassen, weil Mono hat auf der Architektur ab und zu ein paar Fehler hat.
Also es würde mich auch nicht wurden wenn der Fehler durch Little oder Big Endian verursacht wurden ist.

**Comment by ManuelHu** [comment]
Hat in dem Fall vermutlich eher eniger mit der ARM Architektur als mit Mono/.NET zu tun. Gibt mit einem Server in einer Ubuntu VirtualBox (x64) auch so eine Exception. Im Server passiert ja vermutlich auch eine Exception, die aber anscheinend recht gut abgefangen wird (in der Konsole steht nur `Player Testplayer joined the game` und später `Player Testplayer left the game`.

**Comment by tomwendel** [comment]
Mir fehlt leider vollkommen die Erfahrung mit Mono auf ARM. In der Theorie sollte das zwar funktionieren, aber Lassi hat da einen Punkt. Das schlimme: Wenn es ein BigEndian/LittleEndian Problem ist, laufen wir da bei unserer Socket-Lösung auch rein, denn wir werden dort auch den BinaryFormatter für das Serialisieren der Datentypen verwenden. Das würde sogar bedeuten, dass wir uns sogar um den string<->byte[] Convert selbst kümmern müssen. Lasst uns das auf jeden Fall im Auge behalten und testen, sobald wir die ersten Schritte mit Sockets gemacht haben.

**Comment by ManuelHu** [comment]
[Wikipedia](https://de.wikipedia.org/wiki/Byte-Reihenfolge#Hardware-Beispiele) sagt, Windows sei Little Endian. Nach dieser [Antwort auf StackOverflow](http://serverfault.com/questions/163487/how-to-tell-if-a-linux-system-is-big-endian-or-little-endian) ist meine Ubuntu VirtualBox ebenfalls Little Endian. [Der Raspberry ist anscheinend auch Little.](https://www.raspberrypi.org/forums/viewtopic.php?f=2&t=531)

Die Implementierung der `NetTcpBinding`, die wir zur Zeit benutzen, soll unter Mono auch recht buggy sein (hab ich irgendwo mal gelesen, kann aber sein, dass das schon älter war, bei Mono hat sich ja in den letzten Jahren einiges zum Guten gewendet). Vielleicht liegt es ja daran.

**Comment by ManuelHu** [comment]
Ich schließe das mal, weil der alte network sowieso nicht mehr aktuell ist.
