### ISSUE TITLE
Helpprojekt wird nicht unterstützt

### ISSUE THREAD

**Issue by CsharpLassi** [OctoAwesome/octoawesome#121]
Hallo,

Ich hab gerade gemerkt das das OctoAwesome.Help nicht von der Community-Version unterstützt wird.
Eventuell wär es schön, wenn wir solche Projekte die von Verschieden Versionen Abhägen in verschiedene Projektmappen auslaggern. 

Damit wir sicher gehen, das das Hauptprojekt wirklich von allen gelesen werden kann.

**Comment by fnawratil** [comment]
Du meinst VS-Community Version? Du musst Sandcastle installieren damit das geht... Das sollte doch auch in der Community gehen...

**Comment by CsharpLassi** [comment]
Mmmh Sandcastle das könnte klappen muss ich mal bei der nächsten Gelegenheit ausprobieren.
Ich find es nur nicht so schön, wenn man sich erst mal Dinge zusammen suchen muss, weil ich gerade auch nicht sagen kann wie Git in VS damit umgeht.

**Comment by ManuelHu** [comment]
Ja, mit Sandcastle geht's in VS Community.

**Comment by tomwendel** [comment]
Willkommen in der neuen modularen Welt von Visual Studio, Lassi. Sei froh, dass wir noch keine Phone-App, ein Azure Deployment oder was ähnlich "exotisches" drin haben, sondern müsstest du vor dem Build erst noch 4 Extensions installieren.

**Comment by CsharpLassi** [comment]
Die modulare Welt find ich ja prinzipell Klasse, aber mich ärgert es nur, wenn es Projekte gibt die ich nicht öffnen kann, weil ich eine Version hab die nicht 5000€ kostet. ^^

Ich meine nur das wir Vorsichtig sein sollten und eventuell irgendwo sowas vermerken sollten. Hätte @fnawratil und @ManuelHu  das nicht gesagt wüsste ich nicht wie ich das öffnen sollte. 

viele grüße

**Comment by ManuelHu** [comment]
Ich schließe das mal, ist ja kein wirkliches Problem.
