### ISSUE TITLE
Player Position beim Start

### ISSUE THREAD

**Issue by ManuelHu** [OctoAwesome/octoawesome#124]
Beim Start mit einer neuen Welt kommt es vor, dass man im Boden steckt (und der arme Wauzi auch). Das liegt daran, dass im Player-Konstruktor hart die Z-Position auf 100 gesetzt wird, aber die Welt auch höher als 100 Blöcke sein kann. Der Player weiß aber nicht, ob es eine neue Welt ist oder nicht und kann dementsprechend nicht darauft reagieren. Daher müsste man entweder
* Im `CreateUniverseScreen` nach dem Generieren die Position setzen (Blöd für späteren Server-Betrieb)
* Im Player einfach eine höhere Startposition setzen, dass er dann auf die Landschaft runterfällt.

**Comment by tomwendel** [comment]
Ja, das ist doof. Ich würde vorschlagen wir schauen beim ersten Platzieren einfach nach wie hoch die Welt an dem Punkt ist und setzen das ordentlich.

**Comment by ManuelHu** [comment]
Reproduzierbar z.B. beim Seed `583189267`.

@tomwendel Aber bloß wo? Im `CreateUniverseScreen` haben wir keinen `LocalChunkCache` über den wir die Column laden könnten um die Höhe zu finden. Im `ActorHost`, wo wir einen Cache haben, haben wir aber nicht die Information, ob der Spieler gerade zum ersten Mal in diese Welt eingefügt wird. Im `Player` erst recht nicht. Und pauschal bei jdem Start den Player nach oben zu setzen, ist auch nicht so toll, man kann ja auch in einer Höhle stehen...

**Comment by tomwendel** [comment]
Gute Frage. Thematisch gehört es in den ActorHost. Ich würde dem InsertPlayer-Call vielleicht einen "FirstTime"-Flag mitgeben oder so?

**Comment by ManuelHu** [comment]
Ich arbeite gerade an einem dementsprechenden PullRequest. Wird aber etwas mehr, da der `LocalChunkCache` noch keine Mrethoden für Columns hat. Das alte P beamt den Spieler ja auch nur 10 Blöcke hoch.

**Comment by ManuelHu** [comment]
In #127 gefixt
