### ISSUE TITLE
Neue Kollision

### ISSUE THREAD

**Issue by CsharpLassi** [OctoAwesome/octoawesome#128]
Hallo zusamme,

ich hab ein neuen Branch aufgemacht, um meine neue Kollision zu bereitzustellen.

Der Branch stammt noch von dem aktuellen Master-Branch und beinhaltet noch keine NPC-Sachen.

Also meine Bitte an alle: Bitte Testet das ganze mal ob ihr irgendwo was findet was so nicht sein sollte.

Wenn das dann alles Gut ist und Tom das OK gibt merge ich das mit den Master-Branch, wenn die NPC auch im Master sind.

viele grüße
Lassi

**Comment by tomwendel** [comment]
Ach du scheiße wie geil!
Ich hab ein bisschen Angst dass die Planes langsamer sind, würden aber später auch Schrägen erlauben <3 Juhu!

**Comment by tomwendel** [comment]
Gerade ein bisschen rum gewandert und ordentlich gegen Wände gelaufen. Scheint soweit solide zu sein. Mein Go hat es

**Comment by tomwendel** [comment]
...unter der Bedingung, dass wir eine "How it works"-Folge machen ;)

**Comment by CsharpLassi** [comment]
Huch dachte du bist nicht da.
An den Schrägen arbeite ich, aber dazu muss erst was da sein und es fehlen die geeigneten Schnittstellen.

Bei der Performance kann ich dich noch beruhigen, es scheint ein Stück performanter zu sein als deine Variante, aber die Fläche sind auch noch recht einfach gehalten.

Über die Folge können wir reden, war ja schon lange nicht mehr da ^^.

**Comment by jvbsl** [comment]
Ich sag ja immer noch SAT mit minimal translocation vector :D
Muss mir die Kollision aber irgendwann später noch angucken, aber nicht am Handy

**Comment by CsharpLassi** [comment]
@jvbsl :
Ja Ja man kann es auch immer Übertreiben.

**Comment by tomwendel** [comment]
Ich habe mich von Anfang an gegen SAT entschieden weil es überqualifiziert ist für AABB-Kollisionen und dadurch zu rechenaufwendig. Die Frage ist natürlich, ob das wieder zur Option wird, wenn wir in Zukunft auch Kollision mit beliebigen Körpern erlauben wollen.

**Comment by tomwendel** [comment]
Allerdings scheint mir - ich mag mich da irren - die "Minimal Translocation Vector" Auflösung in unserem Fall nicht die beste Variante, weil wir so viele kleine Körper haben die an vielen Stellen aneinander kleben.

Führt mich zum nächsten Optimierungsschritt: Haltet ihr es vielleicht für Sinnvoll aus dem Klötzchenhaufen für die Kollisionsprüfung möglichst sinnvoll größere Körper zusammen zu fassen? Das würde aber ein vollkommen anderes Abfrage-Verfahren erfordern. Octtrees oder so.

**Comment by CsharpLassi** [comment]
Wenn wir uns darauf Beschränken ein Minecraft-Klone zuerstelle, werden unse Objekte immer geometrisch einfach sein. Das komplizierteste Objekt sollte dann nur eine Pyramide oder ähnliches sein. Also können wir auch Algos verwenden die genau auf unsere Probleme abgestimmt sind.

Und wir dürfen auch nicht vergessen, das wir das für die Allgemeinheit machen und sowas geht doch langsam in eine Ebene, wo es nicht mehr für jeden verständlich ist. 
Und man darf nie vergessen o.b.d.a. ^^

Körper zusammenfassen würd ich meinen bringt nichts, kann mich da aber auch irren.

**Comment by ManuelHu** [comment]
Da wir das jetzt im Stream gemerged haben, schließe ich mal das hier.
