### ISSUE TITLE
Rendering Branch

### ISSUE THREAD

**Issue by fnawratil** [OctoAwesome/octoawesome#129]
Nachdem Julian jetzt einen eigenen Branch für Engenious hat und am Rendering Branch seit Dezember nichts mehr passiert ist, denk ich, dass man den entfernen kann...

**Comment by ManuelHu** [comment]
Vermutlich schon, vielleicht sollte man ihn vorher in ein Tag umwandeln um ihn zur Referenz aufzuheben.

**Comment by jvbsl** [comment]
Mein go habt ihr :D
Das hässliche teil braucht man nicht unbedingt mehr

**Comment by ManuelHu** [comment]
Ich machs mal, speichers davor aber als Tag

**Comment by tomwendel** [comment]
Mein Senf noch: Kann weg. Ich glaube nicht, dass es da überhaupt irgendwas gab was verändert wurde. Release und Tag ist also im Grunde auch nicht wirklich notwendig

**Comment by ManuelHu** [comment]
10 Commits wurden in dem Branch gemacht, nachdem er vom master abgezweigt wurde. Ich glaube aber nicht, dass man den jemals noch mal braucht. Selbts trotz GL läuft der ja nicht wirklich plattformunabhängig. Ich lösch dann das Tag.

**Comment by jvbsl** [comment]
Das stimmt nicht ganz, es war komplett Plattform unabhängig,  nur wars nen gefriemel :D
