### ISSUE TITLE
Frage: Wie gehts mit dem Stream weiter?

### ISSUE THREAD

**Issue by fnawratil** [OctoAwesome/octoawesome#130]
Servus Tom,
du hast auf Facebook ja angekündigt, dass es mit den Streams mit der aktuellen Bandbreite so nicht weitergeht. Betrifft das nur die "Let's Code Minecraft" Streams, oder kommt ab jetzt OctoAwesome auch nur mehr offline?

Mfg,
rave

**Comment by tomwendel** [comment]
Servus Rave,

eben erst gesehen. Naja. Der Mangel an Bandbreite ist leider kein exklusives OctoAwesome-Problem :-/ Unter den aktuellen Umständen macht der Stream schlichtweg keinen Sinn - egal ob Octo oder Minecraft. Daher schweren Herzens vorerst beides Offline :(

**Comment by CsharpLassi** [comment]
Ich glaub das Issue können wir schließen, wir wissen ja wie es weiter geht
