### ISSUE TITLE
(kleines) Problem mit engenious 

### ISSUE THREAD

**Issue by SanseroGames** [OctoAwesome/octoawesome#131]
Hallo

Ich habe mal engenious ausgetestet und bin über kleine Probleme gestolpert. Ich habe es auf Windows und Linux (OpenSUSE) getestet. Das kompilieren auf Windows hat funktioniert. Auf Linux meckerte MonoDevelop weil das ContentTool mit einem Fehlercode beendet (129 oder so? Müsste noch mal testen). Auf Windows und auf Linux hab ich allerdings das gleiche Problem, dass wenn ich OctoAwesome starte, das Programm eine Exception wirft, dass GLSL 440 auf meinem System nicht unterstützt wird. Klar, ist jetzt kein zu grosses Problem (Kann ich ja noch updaten), aber erwähnenswert für Userfreundlichkeit und so...

Sansero

**Comment by SanseroGames** [comment]
Das mit dem Content Tool auf Linux könnte auch damit zusammen hängen, dass Linux das Nuget-Package nicht runterladen konnte. Habs dann in VS auf Windows gemacht, aber darum funktioniert es wohl auf Linux nicht...

**Comment by jvbsl** [comment]
Das muss ich mir genauer angucken, also bei mir funktioniert auf Linux das runterladen einwandfrei(und auch das Ausführen, ebenso wie auf Windows). Und ob du es auf Windows oder Linux runterlädst und dann auf dem jeweiligen anderen System ausführst sollte eigt. auch keinen Unterschied machen

**Comment by jvbsl** [comment]
@SanseroGames kann man dich irgendwie außerhalb github kontaktieren, sodass wir das Problem angucken und lösen können?

**Comment by SanseroGames** [comment]
@jvbsl Kann man schon. :D Ähm aber hier will ich meine Kontaktdaten nicht öffentlich posten. Hab dir auf livecoding eine private Nahcricht geschrieben. 
Das der Download des Nuget-Packages nicht funktioniert, liegt ziemlich sicher an MonoDevelop. Weiss nicht, vielleicht mag es meine Xfce Oberfläche oder OpenSUSE allgemein nicht. Kann natürlich auch sein, dass ich bei der Installation was falsch gemacht habe. Bin ja neu bei Linux...

**Comment by SanseroGames** [comment]
So Habs nun endlich hingebekommen. Dass das contentTool auf Linux nicht ausführen wollte, lag daran, dass auf meinem System das Tool nicht automatisch mit mono geöffnet wurde und bash die binäre Datei nicht ausführen konnte. Eine kleine Änderung in einer Datei im engenious-Package, in der ich vor dem ausführen den Befehl mono hingeschrieben habe, konnte ich das Tool schlussendlich trotzdem ausführen. 

Der Fehler wegen der Fehlenden Unterstützung für GLSL 4.40 konnte ich schlussendlich auch beheben, in dem ich auf meinem Linux bumblebee installiert habe. Damit konnte ich Octo auf der NVIDIA statt auf der IntelHD ausführen. Auf Windows wird das vom Treiber her schon unterstützt und geht daher auch.

Tja, damit wäre der das Problem beseitigt. Danke @jvbsl für die Hilfe.
