### ISSUE TITLE
Blockgröße

### ISSUE THREAD

**Issue by CsharpLassi** [OctoAwesome/octoawesome#132]
Hallo,

wir haben ja schon mal im Streamer festgestellt, das die Blockgröße nicht ganz optimal ist.

Ist die Frage ob wir nochmal daran rum schrauben wollen...

Ich sehe im Grunde nur 2 Möglichkeiten, wenn wir es verändern wollen. Entweder auf 1m Blöcke oder wir führen bei Zeiten Werkzeuge ein die 3x3 Blöcke oder so abbauen.

Vielleicht habt ihr ja auch noch ein paar Ideen.

viele grüße
Lassi

**Comment by ManuelHu** [comment]
Ich galube die 50cm sind schon ein gutes Maß - sie erlauben mehr filigrane Kreativität und so ganz Minecraft-klonig wollen wir doch auch nicht werden ;-). Werkzeuge die 3x3 Blöcke abbauen erscheinen mir da sinnvoller, in Wirklichkeit gibt's ja auch Schaufeln und Bagger. Das sollten wir dann berücksichtigen, wenn wir das ganze Inventar & Crafting Zeug noch einmal/zum ersten mal angehen.

**Comment by CsharpLassi** [comment]
@ManuelHu Also bis jetzt hebt es sich noch nicht zu stark ab. Aber ich denke wir sollten vielleicht relativ bald da zu Werkzeuge mal übergehen. Weil es ist auch meine bevorzugte Methode.

**Comment by ManuelHu** [comment]
Wir haben bis jetzt ja noch _nichts_ wirkliches in die Richtung Inventar, Werkzeuge oder Crafting gemacht (mal ausgenommen die Blocks im Inventar). Die alten Sachen die wir dazu mal gemacht hatten sind nur halbfertig uns müssen sowieso komplett überarbeitet werden. Invenatr hat die meisten Stimmen im Trello Board. Inventar, dann Crafting (zum Bauen der Werkzeuge) und dann eine richtige Implementierung von Werkzeugen & Ressourcen hört sich für mich nach einer guten Strategie an. Klingt nur nach 100 Folgen ;-) Vielleicht kann Tom ja mal was dazu sagen.

**Comment by Gallimathias** [comment]
Die Blockgröße ist jetzt schon lange so und wird denke ich auch so bleiben
