### ISSUE TITLE
Capture Verhalten der Maus

### ISSUE THREAD

**Issue by tomwendel** [OctoAwesome/octoawesome#136]
Nach dem Wechsel von Inventar auf Game Screen wird die Position der Maus im Vergleich zum Screen-Zentrum fälschlicherweise berücksichtigt - das sollte nicht so sein, da der MouseMode im Game auf Captured steht.

Vermutlich ein MonoGameUI Issue

**Comment by Gallimathias** [comment]
Muss man mal prüfen ob das noch aktuell so zutrifft

**Comment by ManuelHu** [comment]
Das Problem tritt mit dem aktuellen OctoAwesome develop-Stand immer noch auf. MonoGameUI ist vom Stand her irgendwas aus Nov. 2016, wahrscheinlich Commit https://github.com/OctoAwesome/monogameui/commit/b9ce90fb950bce96ec2adcbd60f0151781ba30c5.

 Mit einer aktuellen Version von MonoGameUI aus dem `feature/engenious`-Branch tritt das Problem nicht mehr auf, wahrschinlich von @CsharpLassi im Commit https://github.com/OctoAwesome/monogameui/commit/544904daad933b88f7378aee534070572605cb0f gefixt.

@fnawratil hat doch was mit engeniousUI am Laufen. Du müsstest mal Testen, ob es damit geht, der Fix müsste aber theoretisch drin sein.

Für die Zwischenzeit habe ich MonoGameUI wieder zum kompilieren gebracht (der Sound geht mit engenious 0.1.7 wieder mal noch nicht...) und eine aktualisierte Version in meinem Repo bereitgestellt.

**Comment by jvbsl** [comment]
Dann baut den Sound ein. engenious kann inzwischen halbwegs mit Sound umgehen...

**Comment by ManuelHu** [comment]
Gefixt mit 3dffa83

**Comment by jvbsl** [comment]
das hier ist außerdem der aktuelle fix dafür
https://github.com/OctoAwesome/monogameui/commit/a0c76d4bab522ec4f48675c5ec6400a45ad4fb1c
Gibt nur noch Probleme mit SDL(ist aber ein bug in OpenTK, der in einem branch dort bereits gefixt wurde)
