### ISSUE TITLE
Doppelklick auf World Liste

### ISSUE THREAD

**Issue by tomwendel** [OctoAwesome/octoawesome#137]
Im Auswahlscreen für Save Games wäre es hilfreich die Welt bereits durch Doppelklick zu starten. Dieses Feature bietet MonoGameUI allerdings nicht. Vermutlich ist die beste Lösung eine Implementierung in MonoGameUI

**Comment by ManuelHu** [comment]
Auch Enter wär ganz nett...

**Comment by tomwendel** [comment]
stimmt. Enter würde ich aber über key-up implementieren. Double Click wäre eher was für MonogameUI
