### ISSUE TITLE
[WIP] Konsole / Chatcontrol

### ISSUE THREAD

**Issue by fnawratil** [OctoAwesome/octoawesome#143]
Nur als Information dass ich an einer Konsole / Chat Control arbeite... Damit nicht das gleiche Problem wie in AntMe auftaucht :D

Code kommt bald...

**Comment by tomwendel** [comment]
Sehr gute Idee mit dem Issue. Na das ist doch was für den nächsten Stream, oder? Da würde ich mit Aline nämlich mal das UI in Angriff nehmen

**Comment by fnawratil** [comment]
Ich hab zwar schon angefangen ( und das chatfenster komplett fertig, samt dem teil dass notifications angezeigt werden die nach kurzer zeit verschwinden wenn das chatfenster nicht geöffnet ist), wird mit aline aber sicher schöner...

**Comment by tomwendel** [comment]
saucool. Bin gespannt

**Comment by ManuelHu** [comment]
Zum Chat übers Netzwerk sollten wir aber vielleicht so lange warten, bis es auch wirklich Multiplayer gibt. Nicht das es dann wieder zwei unterschiedliche Ansätze gibt.

**Comment by fnawratil** [comment]
Gibt noch keinen wirklichen Chat... Es geht hier nur um die UI implementierung um eine möglichkeit zu schaffen befehle auszuführen... Deswegen auch Konsole...

**Comment by fnawratil** [comment]
@tomwendel Das mit Aline war aber ernst gemeint... Vermutlich ist es sowieso besser das im Stream zu machen. 
Ich bin bei meiner Art der Implementierung auf einige Probleme gestoßen. (Sowohl wegen den (begrenzten) Möglichkeiten von MonogameUI, als auch generell...)

**Comment by tomwendel** [comment]
Ah, jetzt lese ich das auch vollständig. Sorry für das Missverständnis gestern im Stream. Ich war der Meinung du bist da schon kurz vor Pull Request.
