### ISSUE TITLE
Networking

### ISSUE THREAD

**Issue by CsharpLassi** [OctoAwesome/octoawesome#144]
Hallo, 
weil mir ja der Develop branch ja schon lange auf den Geist ging, hab ich ihn mal in einen neuen Branch überführt und Develop neu angelegt.

Es ist aber fraglich wie weit er überhaupt noch sinnvoll ist, eventuell könnte er auch ganz weg.

**Comment by ManuelHu** [comment]
Ein paar Dinge aus dem Branch gibt es schon, die noch nicht im master sind:
* UI-Mods
* Crouch / Sprint
* Server UI ließe sich evtl. weiterverwenden

Sollten wir einmal mit einem neuen Neworking beginnen, wäre es vielleicht noch interessant zu schuen, was man im Vergleich zum alten besser machen kann.

Ich weiß aber nicht, wie sinnvoll der neue develop denn ist. Die Features werden ja zur Zeit in den feature-Branches schon bis zur Stabilität entwickelt und erst dann in den master gemerged. Die anderen Pull Requests sollten eigentlich auch ganz stabil laufen. Dadurch kann eigentlich ein relativ stabiler Stand im master gehalten werden. 
Man bräuchte für Gitflow noch einen "Rhytmus" in den man den master branch auf den aktuellen develop Stand bringt, was ohne (derzeit) festgelegte Version auch darauf herauslaufen würde, dass dies früher oder später nach der Implementierung eines Features durchgeführt wird (was wir ja fast sowieso schon ähnlich haben).
Wir sollten lieber öfter stabile Releases anlegen, wer dann wirklich was sehr stabiles haben will, kann dann darauf zurückgreifen. 
was man im Vergleich zum alten besser machen kann.

Ich weiß aber nicht, wie sinnvoll der neue develop denn ist. Die Features werden ja zur Zeit in den feature-Branches schon bis zur Stabilität entwickelt und erst dann in den master gemerged. Die anderen Pull Requests sollten eigentlich auch ganz stabil laufen. Dadurch kann eigentlich ein relativ stabiler Stand im master gehalten werden. 
Man bräuchte für Gitflow noch einen "Rhytmus" in den man den master branch auf den aktuellen develop Stand bringt, was ohne (derzeit) festgelegte Version auch darauf herauslaufen würde, dass dies früher oder später nach der Implementierung eines Features durchgeführt wird (was wir ja fast sowieso schon ähnlich haben).
Wir sollten lieber öfter stabile Releases anlegen, wer dann wirklich was sehr stabiles haben will, kann dann darauf zurückgreifen.

**Comment by tomwendel** [comment]
Hatte in diesem Augenblick den selben Gedanken. Lasst uns doch den Dev-Branch in einen feature/Networking Branch überführen, den Master in einen neuen Dev kopieren und uns dann an den typischen GitFlow halten. Die Existenz von Develop finde ich weiterhin sinnvoll, da unsere Features keineswegs stable beim Merge sind ;) Und dann kann es ja auch weiterhin zu Seiteneffekten kommen.

Der Master ist dann wirklich nur für "Releases".

**Comment by ManuelHu** [comment]
Ich schließe das mal, der Branch ist mittlerweeile ja verschoben.
