### ISSUE TITLE
Engenious Integration

### ISSUE THREAD

**Issue by jvbsl** [OctoAwesome/octoawesome#146]
feature/engenious branch
removing blocks needs to be tested on different devices and platforms.
new array buffer resize worked flawlessly for me:
Linux Mint 64 Bit
NVidia 940M

**Comment by ManuelHu** [comment]
Windows 10 x64, Nvidia GT 730 mit aktuellem Stand aus dem feature-Branch:

    Ein Ausnahmefehler des Typs "System.MissingMethodException" ist in OctoClient.exe aufgetreten.

    Zusätzliche Informationen: Methode nicht gefunden: "Void engenious.Graphics.Texture2D..ctor(engenious.Graphics.GraphicsDevice, Int32, Int32, engenious.PixelFormat)".

Marker bei `ScreenComponent.cs`, Zeile 24. Anscheinend kann er keine 1x1 Pixel große Textur in initialisieren (bzw. findet den Konstruktor nicht), das macht nämlich `base.LoadContent()`.

---
Außerdem referenziert OctoAwesome.Tests noch engenious 0.0.1.15.

**Comment by jvbsl** [comment]
Danke fürs testen, interessanter Unterschied zwischen Mono und .Net, war aber tatsächlich nicht ganz die richtige DLL, Mono hat den Aufruf trotzdem getätigt(Enums als ints behandelt, somit gab es den Konstruktor)
Hab das hoffentlich behoben durch den neuen Push.

Um OctoAwesome.Tests will ich mich nur auf Windows kümmern, das letzte mal manuell Updaten von nuget ging nur schief.(Und die Tests Projekte kann ich in MonoDev ja nicht laden) - feel free.

Nochmaliges testen wäre super ;)

**Comment by ManuelHu** [comment]
Jetzt gehts, danke.

Aber noch ein paar Sachen, die mir aufgefallen sind:
* Umlaute gehen nicht
* Alt+F4 geht nicht
* Scrollen ist total langsam

**Comment by jvbsl** [comment]
Umlaute gehen inwiefern nicht? Kannst du keine in TextBoxen eintippen, oder weil diese verschoben sind?
Alt+F4 geht auf Linux, ich hab keine Ahnung wie ich das auf Windows fixe(evtl. manuell Code hinzufügen)
Welches scrollen meinst du, in Controls? Ist das etwa mit dem master flüssiger?

**Comment by ManuelHu** [comment]
Es werden keine Umlaute auf Buttons angezeigt: Zurück -> Zurck.
![](https://cloud.githubusercontent.com/assets/10050780/17218888/a1f6550a-54e9-11e6-9bd5-0760d59cce69.PNG)
Z.B. die Crew Liste scrollt ganz langsam, der Balken bewegt sich vielleicht 5mm, wo ich im master schon ganz durch die Liste gescrollt habe.

Der Buffer Resize funktioniert uch nicht so, wie er sollte: Nach langem Laufen wird Mist produziert. Manche Chunks werden nicht angezeigt und andere werden dort angezeigt, wohin sie nicht gehören:
![](https://cloud.githubusercontent.com/assets/10050780/17219085/57499a8e-54ea-11e6-8f65-5230fde59d2e.PNG)
![](https://cloud.githubusercontent.com/assets/10050780/17219092/5e78bc18-54ea-11e6-8559-09328e811718.PNG)

**Comment by jvbsl** [comment]
Danke für deine Geduld :D
Um die Umlaute muss ich mich sowieso mal kümmern, aber warum der auf Windows(ich vermute es liegt am OS) ganz fehlt ist mir ein Rätsel, dafür muss ich wohl doch mal wieder auf Windows starten...*sigh*^^

Linux OpenGL verzeiht mir meine Fehler mal wieder wesentlich großzügiger und lässt mich in Memory schreiben, der mir nicht gehört - Ich hoffe die Änderung hat das gefixt.
(Hier bei mir war der Fehler wesentlich schwerer zu reproduzieren und dann nicht in solchem Ausmaß)

Das mit dem Scrolling kann ich leider bei mir auch nicht nachvollziehen, werde ich dann gucken wenn ich das nächste mal auf Windows bin
(Dafür ist mir etwas anderes aufgefallen - die scrollbar reagiert bei mir an der falschen stelle auf events)

**Comment by ManuelHu** [comment]
* Den Fehler mit den fehlenden/kaputten Chunks kann ich nach dem Fix nicht mehr reproduzieren.
* Alt+F4: Auch MonoGame [hat da eine eigene Implementierung für OpenTK](https://github.com/MonoGame/MonoGame/blob/master/MonoGame.Framework/Desktop/OpenTKGameWindow.cs#L209).
* Ich meine das Scrollen mit dem Mausrad. Per Maus halten und Ziehen geht gleich gut (Ruckelt auch ca. gleich viel). [Ein kleines Testvideo dazu (das starke Ruckeln kommt von der Aufnahme)](https://gist.githubusercontent.com/ManuelHu/8d225d8d04e80bc7cc9387e20cd57d58/raw/66b49528c264bb50c30cd50bd0b1586aecb15416/OctoScrollTest.mp4). Zuerst mit Mausrad und danach mit Ziehen, da erkennt man die Geschwindigkeitsunterschiede (Gescrollt wurde immer ungefähr gleich schnell).

**Comment by jvbsl** [comment]
- Alt+F4 hab ich lokal zumindest mal eingebaut
- Das scrollen mittels Mausrad liegt denke ich daran, dass Windows auf basis von 120er schritten arbeitet, die Engine aber in 1er schritten. Jedoch ist mir dabei aufgefallen, dass auf Linux(zumindest bei mir) überhaupt kein Scrolling mittels Mouse.GetState funktioniert, nur mittels event, dabei bin ich noch am Überlegen, wie man soetwas am besten löst

**Comment by ManuelHu** [comment]
- [X] Buffer resize
- [X] ALt+F4
- [X] Scrollen mit Mausrad geht normal
- [ ] Umlaute
- [ ] Windows icon

Ich habe die Issue mal in was generischeres umbenannt, geht ja immer mehr Richtung engenious "merge blockers".

**Comment by ManuelHu** [comment]
Zum Icon:
![](https://cloud.githubusercontent.com/assets/10050780/17785169/f5583b86-657f-11e6-9100-f0551f0be366.PNG)

**Comment by ManuelHu** [comment]
Icon geht jetzt, Umlaute leider noch nicht. Nach löschen von Debug- und Content/bin-Verzeichnissen und neu Kompilieren fehlen unter `Skin.Current.TextFont.Characters` immer noch ä, Ä, ö, Ö, ü, Ü, ß.

**Comment by jvbsl** [comment]
Ok, das ContentTool hat auf Windows nicht korrekt funktioniert(Default-Encoding ist auf Linux nicht das gleiche wie auf Windows -> Utf8 passt hoffentlich generell)

**Comment by ManuelHu** [comment]
Läuft!

**Comment by tomwendel** [comment]
Soweit ich das jetzt überprüfen konnte läuft jetzt Fullscreen, Alt+F4 und das Icon richtig gut. Gamepad aber noch nicht. Und beim Rendern der neuen Schrift habe ich noch das eine oder andere Space-Problem zwischen einzelnen Buchstaben.
![font](https://cloud.githubusercontent.com/assets/2411364/17836817/522a6868-679f-11e6-80cb-2dc5eb21ffe6.png)

**Comment by ManuelHu** [comment]
An manchen Stellen sieht es auch so aus, als wären die Buchstaben leicht auf unterschiedlichen Höhen (z.B. bei "Move Left" das t).

**Comment by jvbsl** [comment]
Vielleicht lade ich die Fonts ja doch einfach falsch, muss ich mal rein gucken, über Hilfe bin ich auch dankbar, ist mein erster Font Renderer :P

**Comment by ManuelHu** [comment]
Bei mir ist das Scrollen wieder total langsam, das hat Tom auch schon im Stream bemerkt ("Ach, das Scrollen geht nicht").
Das Textrendering ist zwar beim Lesen längerer Texte (z.B. in der Crew) störend, aber im Spiel nicht wirklich negativ auffallend (sind immer nur kurze Wörter. Außerdem ist es super, dass der fette Font endlich geht (ist eigentlich irgendwem aufgefallen, dass der unter MonoGame gar nicht ging?).

**Comment by tomwendel** [comment]
Wir hatten die fette Schrift verwendet? :D Ok. Dann ist mir nicht aufgefallen, dass es geht/nicht geht. Aber wir haben auch weiterhin noch die fehlenden Chunks. Da ist also noch was futsch mit der Chunk-Erstellung.

**Comment by ManuelHu** [comment]
Mir ist noch aufgefallen, dass manchmal, wenn man nach Spielstart einen Block entfernt (v.a. wenn man erst mal von oben fällt), der Chunk verschwindet (zumindest graphisch - Kollision geht):

![](https://cloud.githubusercontent.com/assets/10050780/19015096/b2de8de6-87fd-11e6-9ef8-8cb5aef09ba2.PNG)

Komischerweise ist dann die nächst untere Schicht zu sehen, die ja eigentlich gar nicht gerendert werden sollte, weil ja noch andere Blöcke drüber sind.

Und ja, auch fehldende Chunks gibts immer noch. Durch Rechtsklick in die Leere lässt sich ein Chunk "herbeizaubern". Machmal ist es dann auf Anhieb der richtige, manchmal muss man es aber öfter wiederholen.

**Comment by jvbsl** [comment]
![bildschirmfoto vom 2016-10-03 13 21 46](https://cloud.githubusercontent.com/assets/13928225/19035905/c9e98746-896c-11e6-959c-744b82f82f98.png)
Testweise mal das neue FontRendering(mithilfe von @fnawratil und gruenes_schaf) in OctoAwesome laufen lassen. Hat natürlich aktuell keine Effekte wie Schattierungen oder Umrandungen.

**Comment by tomwendel** [comment]
Boa. ihr müsstest das streamen. Das sind coole Arbeiten

**Comment by fnawratil** [comment]
Da stimmt aber das Kerning bzw. XAdvance immer noch an manchen stellen nicht...

**Comment by fnawratil** [comment]
Abgesehen davon bleibt die Frage ob man die aktuell generierten Schriften wirklich auch in Octo verwenden will... Momentan ist im Bitmap ja noch alles in einer Zeile...

**Comment by ManuelHu** [comment]
Irgendwie ist euer Font für die Überschrift zu klein - aber sonst sieht es viel besser aus als davor.

**Comment by fnawratil** [comment]
@jvbsl kann SharpFont überhaupt solche Effekte?

**Comment by jvbsl** [comment]
Das ganze war ja nur mal um zu gucken wie der Fließtext jetzt aussieht. Das ist nichts was ich so pushen werde ;)
@fnawratil libfreetype hat die ganzen Effekte, ich geh mal davon aus, dass man die in SharpFont ebenfalls verwenden kann.
Ich seh ehrlich gesagt nicht, was mit der Font noch nicht stimmt, aber ich hab ja auch nicht wirklich geguckt wie es zu Rendern hat, sondern viel mehr nur experimentiert, bis es gut aussah :D(Können wir ja dann im TS diskutieren)

**Comment by ManuelHu** [comment]
Seit 17b2c1c5cbc99f044139613f268a2086a7d42edf bekomme ich von VS folgende Fehlermeldung:
```
Fehler
Der Befehl " "../tools/net40/ContentTool.exe" /@:"F:\Repos\octoawesome\OctoAwesome\OctoAwesome.Client\Content\Content.ecp" /outputDir:"F:\Repos\octoawesome\OctoAwesome\OctoAwesome.Client\Content\bin\Debug" /intermediateDir:"F:\Repos\octoawesome\OctoAwesome\OctoAwesome.Client\Content\obj\Debug" /projectDir:"F:\Repos\octoawesome\OctoAwesome\OctoAwesome.Client\/" /hidden:true" wurde mit dem Code 3 beendet.
```
Außerdem besteht es darauf, die ProjectGuid in OctoAwesome.Tests.csproj in `{0468B67C-E076-4B19-833C-382513606A5A}` zu ändern.

**Comment by jvbsl** [comment]
Mal probiert das manuell übers ContentTool zu öffnen und damit zu compilen?

**Comment by ManuelHu** [comment]
Mit dem ContentTool standalone läufts einwandfrei, die Dateien werden richtig generiert. Trotzdem liefert VS den Fehler. 

Lt. [einer Website](http://www.febooti.com/products/automation-workshop/online-help/events/run-dos-cmd-command/exit-codes/):
> 3	The system cannot find the path specified. Indicates that the specified path can not be found.

**Comment by ManuelHu** [comment]
Mir ist noch etwas aufgefallen: Es wird immer ein englisches Tastaturlayout verwendet.

**Comment by jvbsl** [comment]
Ist mir jetzt noch nicht aufgefallen, ich dachte ich hätte umlaute in der textbox schon probiert

**Comment by ManuelHu** [comment]
Textboxen gehen, KeyDown usw. liefert aber z.B. z statt y als Key (zum Testen z.B. die Keybindingsseite in den Optionen benutzen)

**Comment by Gallimathias** [comment]
Ich schließe das jetzt mal, das sah mir nach engenious Fehlern aus. Wenn davon noch was offen ist bitte in Engenious als Issue aufmachen.
