### ISSUE TITLE
File Header

### ISSUE THREAD

**Issue by tomwendel** [OctoAwesome/octoawesome#147]
Wir sollten für jede Datei die wir speichern einen Intro-Text + Version einbauen, um schnell den Dateitypen identifizieren zu können.

**Comment by TupperBox** [comment]
@tomwendel Ist das Issue noch aktuell ? Würde mich da morgen, also heute mal dransetzen.

**Comment by tomwendel** [comment]
Ist noch aktuell, ja :)

**Comment by TupperBox** [comment]
Also brauchst du irgendwas, was jegliche Art von StringArrays in eine Datei gießt und nen Header oben drüber ballert und beim Lesen den Header wieder weg wirft, dass das StringArray da wieder raus fällt ?

**Comment by tomwendel** [comment]
Würde vorschlagen eine kleine Zeichenkette im ASCII-Format (je nach Datei-Typ OCTOMAP, OCTOBLI und OCTOBLA), gefolgt von einem Byte als Version oder so. Beim Laden kann dann verifiziert werden, ob a) der Dateityp stimmt und b) der richtige Deserializer für die entsprechende Dateiversion ausgewählt werden.

Also bitte nicht einfach einlesen und wegwerfen, sondern schon mal den Weichenprozess für potentiell neuere Versionen berücksichtigen.

**Comment by ManuelHu** [comment]
@TupperBox es sind keine StringArrays, sondern Rohe Bytes (z.B. aus einem gzip-Stream oder aus dem ChunkSerializer). Der Header sollte aber auch schon vor dem Dekomprimieren lesbar sein.

**Comment by TupperBox** [comment]
Ich denke, ich habe verstanden, worauf ihr hinaus wollt. 
Es wäre also am Einfachsten einen neuen BinaryWriter zu implementieren, denke ich. Habe im ersten Anlauf nicht nachgedacht, Sorry. :)

**Comment by ManuelHu** [comment]
Wir schreiben momentan einiges (ich glaube Chunks und Player) mit dem BinaryWriter. Damit mach eine Erweiterung davon Sinn, mit Konstruktor parameter oder so. Die universe.info schreiben wir aber mit dem XmlSerializer!

**Comment by TupperBox** [comment]
Dann fang ich damit erstmal an.

**Comment by tomwendel** [comment]
Kanonen auf Spatzen! ;) Header und Version würde ich zuerst direkt aus dem File Stream lesen (ASCIIEncoding produziert einen passenden Bytearray) und erst dann den Binary Writer bzw. Zip stream öffnen. So bleibt der Header auch per Notepad lesbar

Tiny Keyboard, tiny Message
________________________________
Von: TupperBox<mailto:notifications@github.com>
Gesendet: ‎15.‎09.‎2016 14:44
An: OctoAwesome/octoawesome<mailto:octoawesome@noreply.github.com>
Cc: Tom Wendel<mailto:tom.wendel@rabbitcode.de>; Mention<mailto:mention@noreply.github.com>
Betreff: Re: [OctoAwesome/octoawesome] File Header (#147)


Dann fang ich damit erstmal an.

**Comment by TupperBox** [comment]
Schaue ich mir nachher an. So lange mache ich C# noch nicht.

**Comment by jvbsl** [comment]
einfach feste Headergröße, da kann ja gerne die FileSize rein(größe - header zumindest), damit man weiß wie viel man dann lesen muss, damit kann man später das Laden beschleunigen. Den Header lädt man einfach direkt in ein byte Array über Stream.Read. Evtl. auch in eine Packed-Struct
Vergleich von int ist schneller als von 4 bytes etc.

**Comment by TupperBox** [comment]
Jetzt bin ich endgültig raus, das war zu viel Input :D

**Comment by tomwendel** [comment]
Vergiss die Filegröße. Da ist es mit dem Linux-Entwickler durch gegangen ;) das hilft uns nicht weiter und verkompliziert das speichern, weil wir dann entweder in mem speichern müssen oder ein random access notwendig ist

Tiny Keyboard, tiny Message
________________________________
Von: TupperBox<mailto:notifications@github.com>
Gesendet: ‎15.‎09.‎2016 19:13
An: OctoAwesome/octoawesome<mailto:octoawesome@noreply.github.com>
Cc: Tom Wendel<mailto:tom.wendel@rabbitcode.de>; Mention<mailto:mention@noreply.github.com>
Betreff: Re: [OctoAwesome/octoawesome] File Header (#147)

Jetzt bin ich endgültig raus, das war zu viel Input :D

**Comment by jvbsl** [comment]
Nix ist da durchgegangen, wenn man bereits weiß wie groß es ist, dann kann man alles auf einmal in Memory lesen, was wesentlich schneller ist, außerdem kann man dann später auch alles in ein File speichern, indem dann von den einzelnen Abschnitten die Größe gespeichert wird und mit ner Index-Tabelle am Anfang dürfte der Zugriff schneller sein, als über mehrere Dateien.
Also verkomplizieren würde ich mal stark in Anführungszeichen schreiben :P

**Comment by TupperBox** [comment]
Ich fang erstmal an, sehe das jetzt als Challenge für mich und du, @jvbsl , kannst ja vorm Merge nochmal rüber schauen :)

**Comment by tomwendel** [comment]
Die Filegröße kennen wir ja vom Filesystem. Ein potenzieller Cache wäre dem Deserializer vorgeschaltet und würde dann anstatt einem Filestream einen Memorystream liefern.

Verkomplizieren würde es den Speicherprozess insofern, dass wir die Größe der Datei dank Zip noch nicht kennen. Wir müssten also nachträglich zum Header springen und schreiben oder erst mal alles in memstream packen und nochmal kopieren. Ersteres ist schlecht für Streaming, letzteres macht es langsamer

Tiny Keyboard, tiny Message
________________________________
Von: jvbsl<mailto:notifications@github.com>
Gesendet: ‎15.‎09.‎2016 19:45
An: OctoAwesome/octoawesome<mailto:octoawesome@noreply.github.com>
Cc: Tom Wendel<mailto:tom.wendel@rabbitcode.de>; Mention<mailto:mention@noreply.github.com>
Betreff: Re: [OctoAwesome/octoawesome] File Header (#147)


Nix ist da durchgegangen, wenn man bereits weiß wie groß es ist, dann kann man alles auf einmal in Memory lesen, was wesentlich schneller ist, außerdem kann man dann später auch alles in ein File speichern, indem dann von den einzelnen Abschnitten die Größe gespeichert wird und mit ner Index-Tabelle am Anfang dürfte der Zugriff schneller sein, als über mehrere Dateien.
Also verkomplizieren würde ich mal stark in Anführungszeichen schreiben :P

**Comment by jvbsl** [comment]
das eine mal seeken und schreiben ist verhältnismäßig schnell und das wichtige ist, dass beim Speichern die Geschwindigkeit nicht so wichtig ist wie beim Laden.
Für das auslesen der Dateigröße aus dem FileSystem braucht es länger und aus der Datei selbst braucht man ebenfalls nen Seek.

**Comment by TupperBox** [comment]
Okay, ich habs soweit, dass ich einen neuen FileStream implementiert habe, der die Header ließt und schreibt. Habe 32 Byte als Header im Moment gewählt. 

Wenn ich eine Zahl als Byte speicher, zeigt mir diese mein TextEditor nicht an, logischerweise. Wenn der ganze Kram aber lesbar sein muss, müsste ich den Spaß ja einmal als ASCII und einmal als Byte speichern oder gibts da nen schlaueren Weg ?

**Comment by jvbsl** [comment]
Beim speichern kannst du wegen mir ruhig chars nehmen. Und wenn man es als int nimmt musst du einfach die entsprechenden ASCII Werte nehmen:
0x4F43544F für OCTO

**Comment by TupperBox** [comment]
> ASCIIEncoding produziert einen passenden Bytearray

Ich kippe den String mit der Methode, welche Tom vorgeschlagen hat, in mein byte-Array. Und wenn ich eine Zahl mit in den String aufnehme, wird diese auch geschrieben und ist sichtbar.

Eine sehr, sehr, sehr rudimentäre Lösung wäre einfach, dass man sich nen String zusammenbaut und Diesen als Header speichert und dann als String wieder ließt und dann auseinanderbaut.

**Comment by tomwendel** [comment]
Letzte Rückmeldung für heute ;)

@jvbsl: Ein Seek ist leider nicht immer möglich (z.B. bei einem Austausch der Daten mit der Cloud), weshalb ich gerne mit einem sequenziellen Schreibvorgang arbeiten würde. Ich sehe zwar deine Sorge, dass ein Read einzelner Bytes langsamer ist als ein Read der vollen Datei, aber sollte das nicht das Betriebssystem halbwegs im Griff haben? Frage also: Ist es wirklich signifikant schneller, wenn ich erst alles auf einmal lese?

@TupperBox: Ich bevorzuge bei Headern die Lösung über den ASCII-Encoder. Write(string) schreibt in der Regel die Länge des Strings vorweg, was als Header irgendwie unpassend ist. Außerdem erfordert der Write per BinaryWriter die Existienz eines BinaryWriters. Wir müssten also, bevor wir überhaupt wissen mit welchem Verfahren der restliche Body codiert ist (kann ja von Version zu Version unterschiedlich sein) bereits einen BinaryReader auf den Stream hängen.

Ich bin mir nicht ganz sicher auf welcher Framework-Version wir bei Octo sind, aber unter 4.0 schließt der BinaryReader beim Close auch automatisch den darunter liegenden Stream, was beim Lesen des Headers fatal wäre.

Die wesentlich interessantere Frage in diesem Zusammenhang bleibt aber, wie das passende Interface für die Versionsweiche aussieht. Wir müssen nämlich unterschiedliche Deserialisierungsmethoden in Abhängigkeit der Protokoll-Version aufrufen. Ich verweise mal auf meine dazu passende Lösung in AntMe!: https://github.com/AntMeNet/AntMeCore/blob/develop/src/AntMe.Core/Serialization/MapSerializer.cs

Gute Nacht zusammen

**Comment by jvbsl** [comment]
Nunja das "Seeken" ist ja wie gesagt nur für einzelne Chunks und dann eben eine Sache von Networking und nicht wie die Datei gehalten wird.
Naja einzelne Bytes werden wir aufjedenfall nicht laden, dafür wird ja Buffered gelesen, wenn wir es aber im Vorraus wissen kann man dadurch meiner Erfahrung nach schon Zeit sparen, vorallem nachdem wir ja meist nicht nur einen Chunk laden, da könnte sich das mMn schon auswirken - müsste man dann aber tatsächlich für unseren Anwendungsfall checken.

Der BinaryReader hat einen Konstruktor, dem man sagen kann, dass er den Stream offen lassen soll.

Solang das ganze mit der Version nicht über nen switch geht :-D
Außerdem wäre vlt. nen zweistelliges System sinnvoll, 1.0 wenn sich die letzte Stelle ändert, dann ist die Kompatibilität gegeben sind dann nur bugfixes oder Geschwindigkeitsveränderungen, die nichts an der Kompatibilität zum Serializer/Deserializer ändern und die erste Versionsnummer ändert tatsächlich die Kompatibilität(ob wir über die nicht so drastischen Änderungen über die Versionsnummer tracken wollen, lässt sich natürlich noch diskuttieren)

**Comment by TupperBox** [comment]
Vielleicht ist meine Auffassung von diesem Problem viel zu simpel, aber Folgendes würde es doch erstmal tun, oder ?

 #160

**Comment by tomwendel** [comment]
Servus zusammen. Naja, der Weg als Spezialisierung von FileStream macht die Idee der Quell-Abstraktion kaputt. Dein Ansatz funktioniert nur mit Files, sollte aber grundsätzlich mit allen Streams klarkommen. Deswegen wollte ich es auch gar nicht übertreiben und die Versionierung auf Basis des Persistierungs-Manager machen.

**Comment by TupperBox** [comment]
Das sollte theoretisch ja auf allen Streams laufen. Mache da ja keinen großen HokusPokus mit.

**Comment by TupperBox** [comment]
Würdest du dich also mit einer allgemeinen Stream-Implementierung zufrieden geben ? 
Ich bin total unsicher, was du und was @jvbsl erwarten. Deine Implementation in AntMe! ist recht einfach und simpel und ich habe die Idee aufgegriffen und auf Streams umgebogen..

**Comment by tomwendel** [comment]
Also wenn es unbedingt eine Stream-Überladung sein muss, dann doch einer, der das Ganze aus einem anderen Stream durch schleust. Ich sehe die Schwierigkeit bei diesem Problem nicht beim Schreiben und Lesen des Headers, sondern bei der korrekten Steuerung und Weichenstellung beim Laden und Speichern unterschiedlicher Versionen. Bei der Implementierung sind mir 2 Dinge wichtig:

a) Dass Daten in und aus beliebigen Streams gelesen werden können. Das muss mit FileStreams, NetworkStreams oder wie @jvbsl vorschlägt auch mit gecachten Daten (Also MemoryStreams) funktionieren.

b) Je nach Dateiversion müssen vollkommen unterschiedliche (De)Serialisierer mit vollkommen unterschiedlichen Lese/Schreibe-Strategien möglich sein. Das inkludiert auch vollkommen unterschiedliche Protokolle. Das könnte das sein, was wir aktuell haben, später aber auch gerne das implementieren, was @jvbsl vorschlägt (also komplette Streamgröße oder Checksummen im Header). Wenn man dem Deserialiserer "nur" einen BinaryReader/Writer gibt, wird das alles sehr unflexibel. Da muss also ein Stream rein und der Deserialisierer soll dann machen was er will.

Also wenn eine Implementierung als Stream, dann bitte nach dem Vorbild des ZIP-Streams. Also Quell-Stream im Konstruktor und dann Durchreichen der Lese-/Schreib-Zugriffe.

**Comment by CsharpLassi** [comment]
Wir weiter im Issue #215 bearbeitet.
