### ISSUE TITLE
Gedaken zu ExtensionManager und TexturePacks

### ISSUE THREAD

**Issue by ManuelHu** [OctoAwesome/octoawesome#148]
Bis jetzt versucht der `ExtensionManager` alle .dll-Dateien im Programmverzeichnis (und im `plugins`-Verzeichnis) zu laden. Um später ein UI dafür anbieten zu können, sollte dieses Verhalten m.E. nach angepasst werden. Dazu einige Möglichkeiten, die mir eingefallen sind:

1. Man lädt nur Erweiterungen aus einem bestimmten Verzeichnis (Ich würde aber `Extensions` statt `plugins` vorschlagen).
1. Man lädt nur DLLs deren Dateiname mit `OctoAwesome.` beginnt.
1. Man lädt alle DLLs, zeigt aber nur die, deren Dateiname mit `OctoAwesome.` beginnt, an (Sicherheitsproblem: Schadcode könnte sich so verstecken).
1. Man lädt nur DLLs, die eine Klasse, die von einer bestimmten Schnittstelle erbt (z.B. sowas wie `IExtension`), enthält. Diese Klasse könnte dann noch weitere Informationen zu Extension halten (Autor, Lizenz...)

Dann könnte man in der `App.config` mit `ExtensionManager-disable-OctoAwesome.foo.dll = true` das laden einer solchen Erweiterung verbieten.

Über ein UI für den ExtensionManager ließen sich dann auch TexturePacks realisieren:
* Unter `Assets/{Namespacename}` liegt das aktuelle Pack
* Unter `Assets/_old/{Namespacename}/{int}` liegen versioniert alte Texturepacks. {int} ist einfach eine fortlaufende Ganzzahl.
* Durch Verschieben der Ordner und Neustarten der Applikation wird dann das neue TexturePack aktiviert.
* In jedem Pack liegt eine Datei `designer.info`, die Informationen zum Autor und zum Pack enthält (Name, Version, Lizenz, Webadresse). Die Daten werden im Spiel angezeigt.

Was haltet ihr davon?

**Comment by jvbsl** [comment]
5. man kann die Extension Assemblies auch mit einem entsprechenden Assembly-Attribut verpassen, damit wir frühzeitig bei einer Dll entscheiden können, ob diese für uns nützliche Informationen enthält

Bei den Assets würde ich lieber Asets/{Namespacename}/{Version} generell machen, welche dann geladen wird kann der User entsprechend auswählen(kann ja sein, dass ein neues verbuggt ist oder sonst was). Und welches dann ausgewählt ist wird irgendwo extra gespeichert. Außerdem denke ich lässt sich ein Neustart der Applikation hoffentlich verhindern ;)

**Comment by ManuelHu** [comment]
Das mit den Attributen klingt sehr gut.

Das mit der Version generell im Namen hat nur einen Haken: Die Extensions laden bis jetzt _selbstständig_ ihre Assets (Bsp. BrickBlockDefiniton):
```c#
return (Bitmap)Bitmap.FromFile("./Assets/OctoAwesome.Basics/Blocks/brick_red.png");
```

Dann müssten die Extensions Informationen darüber bekommen, aus welchem Ordner sie etwas zu laden haben (quasi Zugriff auf dem ExtensionManager). Der liegt aber in der Runtime.

Zum Neustart: Wenn man direkt nach dem Starten des Spiels in die Optionen geht und ein TexturePack auswählt brauchts keinen. Wenn aber aus dem geladenen Spiel in die Optionen gewechselt wird, sind die Texturen schon im Speicher (ähnlich wie Viewrange).

Es geht auch weniger um Versionen, sondern eher um eindeutige Indentifizierer (evtl. Guid?), dass halt das paket von Desiger A vom Paket von Desiger B unterschieden werden kann (oder auch von einem anderen von Designer A).

**Comment by tomwendel** [comment]
Der Ansatz mit dem Attribut löst nicht das eigentliche Problem das wir mit selektiven Extensions (inkl. konkurrierenden Versionen) haben. Um das Attribut auszulesen müssen wir das Ding leider schon geladen haben. Ich sehe folgende Ansätze:

Manuels Ansatz mit der Naming-Convention bzw. das Laden aus bestimmten Verzeichnissen ist schon mal der erste Schritt. Wenn wir jetzt aber Extension-Infos auslesen wollen ohne die Assembly gleich zu laden, fallen mir 3 Optionen ein:

- Die Assembly kommt nicht alleine sondern in einem Package (vielleicht ZIP) das neben der dll auch eine info-Datei enthält, praktischerweise vielleicht sogar ihre eigenen Assets. Das ist der Ansatz den auch Minecraft verfolgt und der mir auch am besten gefällt.

- Wir verwenden ein Identifizierungskonzept innerhalb der Assembly - beispielsweise Julians Assembly-Attribut. Dann müssen wir zur Identifikation diese DLL aber irgendwie selektiv laden. In AntMe! lade ich beispielsweise Ameisen in App Domains um die Meta-Daten zu instanziieren und auszulesen und anschließend die DLL wieder entladen zu können. Das ist aber leider nicht ganz so einfach dank Referenzen und so. (schlechteste Lösung)

- Wir laden weiterhin alle DLLs, zentralisieren aber die Extension-Steuerung mit Hilfe einer zentralen Implenentierung eines IExtension-Interfaces das wir beim Laden suchen. Alle Extension-Elemente (wie beispielsweise eine BlockDefinition) werden in Referenz zur Extension gespeichert und können dann sogar zur Laufzeit ein und ausgeschaltet werden. So mache ich das in AntMe! 2.0. Diese Lösung halte ich für die sauberste, allerdings fehlt hier ein Konzept für die Assets.

**Comment by ManuelHu** [comment]
Konkurrierende Versionen der Extensions waren nicht angedacht. Eher dass eine Extension mehrere TexturePacks (von verschiedenen Designern) hat, die dann ausgetauscht werden. Das ist eigenlich unabhängig von dem Extension-lade-Zeug, das wird aber benötigt, um ein gutes UI dafür zu bauen (damit halt nicht Sharpdx.dll und so angezeigt werden).

Nochmal drei Ideen:

---

* Geladen werden alle Assemblies.
* Angezeigt, instanziert, verwendet und angezeigt werden nur diese, die eine `IExtension` enthalten und damit die anderern Elemente zugänglich machen.
* Die Standard-Assets enthalten die Assemblies in den Ressourcen (Pfad: `Assets/{Namespacename}`
* Über eine `AssetsLoader`-Klasse wird überprüft, ob im Dateisystem eine Datei mit gleichem Namen schon existiert und gibt, falls ja diese Datei zurück, falls nein, die aus dem Ressourcen.

---

* Geladen werden alle Assemblies.
* Angezeigt, instanziert, verwendet und angezeigt werden nur diese, die eine `IExtension` enthalten und damit die anderern Elemente zugänglich machen. Diese Klasse enthält einen Wert für `default-guid`
* Die Standard-Assets liegen im Dateisystem (Pfad: `Assets/{Namespacename}/{default-guid}`). 
* Eine `AssetsLoader`-Klasse löst virtuelle Dateinamen (praktisch so wie sie jetzt sind) auf und lädt sie aus dem Ordner mit der gerade ausgewählten Guid.

---

* Geladen werden alle Assemblies.
* Angezeigt, instanziert, verwendet und angezeigt werden nur diese, die eine `IExtension` enthalten und damit die anderern Elemente zugänglich machen. Diese Klasse enthält einen Wert für `default-guid`
* Die Assets liegen im Dateisystem (`Assets\{Namespacename}`) und werden bei installation eines neuen Packs überschrieben. Wenn man das alte zurückwill muss man es einfach neu herunterladen.

**Comment by tomwendel** [comment]
Inzwischen auch mal wieder etwas Ruhe gehabt um darüber nachzudenken.

IExtension können wir machen - so habe ich es auch bei AntMe! gemacht und eigentlich finde ich das Konzept inzwischen ganz cool. Darüber sind wir uns also einig.

Beim Asset- und Ressourcen-Management würde ich ein bisschen bei Minecraft spicken. Die machen das aus meiner Sicht nämlich ganz gut. Dort gibt es auch diese Verzeichnisstruktur wie bei Assets - nur eben pro Ressource-Pack. Das erlaubt dann auch das überlagern mehrerer Packs gleichzeitig.

Um das zu regulieren wäre ich auch für einen Asset-Manager der auch das Caching und die Umwandlung in eine Texture2D übernimmt. Das spart uns sicher viel Arbeit. Mir gefällt die Idee die Standard-Ressourcen in der Assembly zu haben. So kann sie in IExtension registriert und mit einem Fallback Value ausgestattet werden. Weitere Ressource Packs überschreiben dann (je nachdem, ob im Verzeichnis eine entsprechende Datei vorhanden ist) die Textur.

Die Konvention kann dann sein "Ressources/{Assetpack}/{Namespace}/{Type}/{Assetname}" oder so. Da müssen wir mal sehen wo der Kompromiss aus unnötig lang und möglichst eindeutig liegt.

**Comment by ManuelHu** [comment]
Ich würde in den Ressourcen (also die defaults) unter `Assets/{Namespace}/{Filename}` speichern. Type wäre mir erst mal zu viel, vor allem weil es ja mehrfach verwendete Texturen gibt (z.B. Gras und Schnee haben die selbe untere Textur, oder Button und Tab). 

Die überschreibenden TexturePacks würde ich einfach weiterhin in `./Assets` legen. Darunter dann Guids als Ordnername (weil dann über UI/App.config besser referenzierbar). Dann normal darunter weiter `{Namespace}/{Filename}`. Für jeden Namespace kann man dann auswählen, welches TexturePack (oder default) verwendet wird.

Eine `AssetsManager`-Klasse könnte dann eine Methode `Load(object, string)` haben, die aus dem Objekt mit Reflection den Namespace extrahiert.

Ein Vorschlag der Ladeprozedur:
![prasentation1](https://cloud.githubusercontent.com/assets/10050780/17702186/258788d4-63cd-11e6-8ec2-70510f855656.jpg)

**Comment by ManuelHu** [comment]
Implementiert im gestrigen Stream
