### ISSUE TITLE
Texture/AssetManager

### ISSUE THREAD

**Issue by tomwendel** [OctoAwesome/octoawesome#153]
Aktuell werden an vielen Stellen Dateien geöffnet um Texturen zu laden. Im Hinblick auf Texture-Packs muss das aber zentralisiert werden - auch beim Thema Caching.

**Comment by ManuelHu** [comment]
Wir brauchen auf jeden Fall 3 Methoden:
- `LoadTexture2D` => Laden von UI-Texturen, Toolbar-Bildern...
- `LoadBitmap` => Laden der Bitmaps für die BlockTexture (wird ja dynamisch per Drawing erzeugt)
- `LoadtText` => Crew XML-Datei

Dabei werden nur die Textures gecached, um den Overhead einer erneuten Umwandlung zu umgehen. Die weitere Kaskade (TexturePack, Default) wird aber für alle Typen durchlaufen.
Dabei werden nur die Textures gecached, um den Overhead einer erneuten Umwandlung zu umgehen. Die weitere Kaskade (TexturePack, Default) wird aber für alle Typen durchlaufen.

**Comment by ManuelHu** [comment]
Wir brauchen unebdingt noch eine Methode zum Laden eines Streams (aber mit der selben Ladekaskade wie bei den Texturen auch - nur ohne Cache). Dann könnten wir uns den Assets-Ornder im Ausgabeverzeichnis komplett sparen.

Ich denke, dass die Texturen der Crew-Member-Bilder nicht über den Kontext der ScreenComponent, sondern über den CrewMemberScreen (dann haben wir auch mehr Ordnung in den Dateien.

**Comment by ManuelHu** [comment]
Gestern im Stream abgeschlossen
