### ISSUE TITLE
Inventar: Leeren des aktiven Slots löscht nicht ActiveTool

### ISSUE THREAD

**Issue by ManuelHu** [OctoAwesome/octoawesome#155]
Wenn man den gerade als aktiv markierten Blocktyp aus der Toolbar entfernt, wird das `ActiveTool` des Players nicht zurückgesetzt und man kann den Blocktyp weiter setzen, bis von der Menge nichts mehr übrig ist.

**Comment by tomwendel** [comment]
Gnaaarrrr! Stimmt :D Ich bin der Meinung, dass die ganze Tool-Logik irgendwie mit in Player oder zumindest ins ActorHost muss. Damit würden wir solche Probleme zentralisieren. Ich sehe nämlich später durchaus Probleme auf uns zukommen, wenn die Tools noch von anderen Dingen beeinflusst werden. Vielleicht können ja Inventar-Sachen später verderben oder automatisch verschwinden,...
