### ISSUE TITLE
SettingsManager wird von Methoden genutzt, die nicht im OctoAwesome.Client liegen.

### ISSUE THREAD

**Issue by TupperBox** [OctoAwesome/octoawesome#158]
@ManuelHu hatte vorgeschlagen, dass der SettingsManager eine SettingsComponent wird und wir das in den Client umziehen. 
Allerdings nutzen unter Anderem der DiskPersistenceManager ebenfalls diese Speicherfunktion, welche nicht Teil des Clients sind, somit keine Referenz auf OctoGame besitzen und somit nicht auf die Components zugreifen können.

Wie könnte man weiter verfahren ?

**Comment by ManuelHu** [comment]
Sorry, habs erst jetzt gelesen.

Man könnte den `SettingsManager` von einer Schnittstelle (z.B. `ISettingsManager`) erben lassen (diese müsste dann aber in OctoAwesome liegen - der eigentliche Manager liegt aber im Client). Dann müsste man dem `DiskPersistenceManager` einen `ISettingsManager` im Konstruktor mitgeben, dieser kann vom Client geliefert werden. Dadurch haben wir einerseits gewährleistet, dass Extensions keinen Zugriff drauf haben und dass die Runtime aber schon.

Ein weiterer Vorteil wäre, dass man irgendwann mal Online-Einstellungen haben könnte ohne an die App.config gebunden zu sein.

Außerdem würde ich nicht direkt eine Komponente daraus machen, es reicht auch eine einfache Klasse (vgl. `KeyMapper`), die dann im `Game` gespeichert wird.

**Comment by ManuelHu** [comment]
Siehe https://github.com/ManuelHu/octoawesome/commit/12be21937e4bd3b58bc104241adc1f6c1137591d

**Comment by TupperBox** [comment]
Der `ResourceManager` sollte ja eh kein Singleton bleiben. Das hat Tom im Stream mal gesagt. Im Grunde könnte man das Also so machen. :)

**Comment by tomwendel** [comment]
Mein Vorschlag dazu: Wir packen, wie von @ManuelHu ein Interface (sagen wir mal ISettings) in die OctoAwesome Assembly. Die tatsächliche Implementierung passiert aber, wie auch beim ganzen Persistence Layer in der Runtime Assembly wo dann auch die tatsächliche Implementierung des SettingManagers passiert. Oooooder wir legen die Settings in den Client (was irgendwie sogar noch mehr Sinn macht, da das ja eine client-spezifische Sache ist) und implementieren das tatsächlich als Component. Fände ich den schönsten Weg. So können wir dann auf unterschiedlichen Systemen sogar unterschiedliche Konzepte der Settings-Speicherei verwenden (potentiell denkbar sind z.B. zentralisierte Settings an einem Server oder so).

**Comment by TupperBox** [comment]
Würde ebenfalls den zweiten Ansatz bevorzugen und mich um Umsetzung und
Implementierung, auch, was das Singleton-Problem angeht, kümmern. :)

**Comment by tomwendel** [comment]
Seeeehr cool. Ich danke euch

Tiny Keyboard, tiny Message
________________________________
Von: TupperBox<mailto:notifications@github.com>
Gesendet: ‎18.‎09.‎2016 10:38
An: OctoAwesome/octoawesome<mailto:octoawesome@noreply.github.com>
Cc: Tom Wendel<mailto:tom.wendel@rabbitcode.de>; Comment<mailto:comment@noreply.github.com>
Betreff: Re: [OctoAwesome/octoawesome] SettingsManager wird von Methoden genutzt, die nicht im OctoAwesome.Client liegen. (#158)

Würde ebenfalls den zweiten Ansatz bevorzugen und mich um Umsetzung und
Implementierung, auch, was das Singleton-Problem angeht, kümmern. :)

**Comment by ManuelHu** [comment]
Wir haben jetzt ja eine Lösung
