### ISSUE TITLE
[Bug] Auflösungseinstellung

### ISSUE THREAD

**Issue by TupperBox** [OctoAwesome/octoawesome#162]
Bei Verstellung der Auflösung, sodass ein Teil des Bildes außerhalb des Bildschirms ist, muss nach dem Neustart das Fenster erst bewegt werden, bis die Buttons wieder benutzbar sind.

**Comment by tomwendel** [comment]
Oh... :-(

**Comment by ManuelHu** [comment]
Ich weiß nicht, ob das Problem auf unserer Seite liegt. Bei engenious tritt das Problem nicht auf, wenn man die Größe im Code ändert.

**Comment by jvbsl** [comment]
Bei engenious geht es und bei MonoGame nicht, das ist mal was neues :D

**Comment by tomwendel** [comment]
Und wieder ein guter Grund bald umzustellen. Gibts denn jetzt noch irgend einen ernsten Grund das nicht zu tun @jvbsl ?

**Comment by ManuelHu** [comment]
@tomwendel siehe #146

**Comment by ManuelHu** [comment]
Irgendwie macht engenious jetzt das Fenster gar nicht mehr größer als der Bildschirm maximal groß ist.
Zumindest nicht wie in #170.

**Comment by ManuelHu** [comment]
Engenious ist jetzt endgültig im develop gelandet, der Bug funktioniert dort nicht mehr.
