### ISSUE TITLE
Seltsame Fehler von Monogame ?

### ISSUE THREAD

**Issue by TupperBox** [OctoAwesome/octoawesome#163]
Beim Bauen des Projekts ausm aktuellen develop-Branch, bekomme ich bei allen `FileMode` und `FileAccess` zugriffen einen Fehler, welchen ich nicht beheben kann.

> Der Typ "FileMode" ist in "MonoGame.Framework, Version=3.5.1.1679, Culture=neutral, PublicKeyToken=null" und "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" vorhanden.

**Comment by tomwendel** [comment]
Ergibt auf den ersten Blick keinen Sinn, weshalb ich einfach mal auf ein fehlendes Using tippe?

Tiny Keyboard, tiny Message
________________________________
Von: TupperBox<mailto:notifications@github.com>
Gesendet: ‎18.‎09.‎2016 12:03
An: OctoAwesome/octoawesome<mailto:octoawesome@noreply.github.com>
Betreff: [OctoAwesome/octoawesome] Seltsame Fehler von Monogame ? (#163)


Beim Bauen des Projekts ausm aktuellen develop-Branch, bekomme ich bei allen FileMode und FileAccess zugriffen einen Fehler, welchen ich nicht beheben kann.

Der Typ "FileMode" ist in "MonoGame.Framework, Version=3.5.1.1679, Culture=neutral, PublicKeyToken=null" und "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" vorhanden.

**Comment by TupperBox** [comment]
Das Using ist drin, wird aber einmal von der stdlib geliefert und einmal
von Monogame. Und da weiß ich nicht, wie ich das machen soll.

**Comment by tomwendel** [comment]
Ah, das erklärt es. In dem Fall benutzt du inline einfach den vollen Namespace. Also anstatt FileMode kommt System.IO.FileMode

Tiny Keyboard, tiny Message
________________________________
Von: TupperBox<mailto:notifications@github.com>
Gesendet: ‎18.‎09.‎2016 12:38
An: OctoAwesome/octoawesome<mailto:octoawesome@noreply.github.com>
Cc: Tom Wendel<mailto:tom.wendel@rabbitcode.de>; Comment<mailto:comment@noreply.github.com>
Betreff: Re: [OctoAwesome/octoawesome] Seltsame Fehler von Monogame ? (#163)

Das Using ist drin, wird aber einmal von der stdlib geliefert und einmal
von Monogame. Und da weiß ich nicht, wie ich das machen soll.

**Comment by TupperBox** [comment]
![filemode](https://cloud.githubusercontent.com/assets/12380026/18615150/19f168f0-7d9f-11e6-878d-361cd265e6e4.PNG)

**Comment by tomwendel** [comment]
Öhm. Das ist interessant...

Tiny Keyboard, tiny Message
________________________________
Von: TupperBox<mailto:notifications@github.com>
Gesendet: ‎18.‎09.‎2016 12:55
An: OctoAwesome/octoawesome<mailto:octoawesome@noreply.github.com>
Cc: Tom Wendel<mailto:tom.wendel@rabbitcode.de>; Comment<mailto:comment@noreply.github.com>
Betreff: Re: [OctoAwesome/octoawesome] Seltsame Fehler von Monogame ? (#163)


[filemode]<https://cloud.githubusercontent.com/assets/12380026/18615150/19f168f0-7d9f-11e6-878d-361cd265e6e4.PNG>

**Comment by TupperBox** [comment]
Fehler ist wohl bekannt, kommt wohl von "falschen" Abhängigkeiten, ich habe aber keine Ahnung, was ich jetzt verkehrt mache.

**Comment by tomwendel** [comment]
Beim Thema falschen Abhängigkeiten und komischen Fehlern: Ich hatte auch schon sehr wirre Fehler, weil ich ne falsche Kombination aus MonoGame- und .NET Framework hatte. Du solltest sicher stellen, dass du, wenn du MonoGame 3.5 nutzt auch gegen .NET 4.5 (ich glaube der Dev Branch von Octo steht noch auf 4.0) buildest. Das hat mich schon zum Wahnsinn getrieben.

Tiny Keyboard, tiny Message
________________________________
Von: TupperBox<mailto:notifications@github.com>
Gesendet: ‎18.‎09.‎2016 12:59
An: OctoAwesome/octoawesome<mailto:octoawesome@noreply.github.com>
Cc: Tom Wendel<mailto:tom.wendel@rabbitcode.de>; Comment<mailto:comment@noreply.github.com>
Betreff: Re: [OctoAwesome/octoawesome] Seltsame Fehler von Monogame ? (#163)


Fehler ist wohl bekannt, kommt wohl von "falschen" Abhängigkeiten, ich habe aber keine Ahnung, was ich jetzt verkehrt mache.

**Comment by TupperBox** [comment]
Jo, das war es. Die OctoAwesome.Runtime baut laut Settings gegen den Latest, was bei mir aufm System 4.5.2 war. Der Rest des Projekts baut auch noch gegen 4.5.2 - witzigerweise.

Hab jetzt noch Folgendes: 
> "C:\Users\Johann\git\octoawesome\OctoAwesome\bin\Debug\OctoAwesome.Runtime.dll" wurde nicht gefunden.

**Comment by tomwendel** [comment]
Wird diese Assembly denn korrekt gebuildet? Und vorallem an den richtigen Ort? Soweit ich mich erinnere haben wir zuletzt alles auf Framework 4.5.2 umgestellt und im Output Folder sollte "..\bin\Debug\" stehen.

**Comment by TupperBox** [comment]
Okay, well. Habe jetzt jeden Stein fünfmal umgedreht und jetzt baut es auch bei mir wieder. Baue jetzt wieder alles gegen 4.5.2, warum auch immer..
