### ISSUE TITLE
(I)Settings Erweiterungen

### ISSUE THREAD

**Issue by johannwagner** [OctoAwesome/octoawesome#166]
Get-Methode des SettingsManager soll ein default zurückgeben, wenn nicht vorhanden.

**Comment by TupperBox** [comment]
Im Weiteren können *alle* Methoden generisch werden.

**Comment by ManuelHu** [comment]
Ein paar ungeordnete Ideen:
- [ ] Default Wert
- [ ] Bei nicht-existierendem Key null zurückgeben (zur Zeit Exception)
- [ ] Tests fixen
- [ ] Löschen von Keys
