### ISSUE TITLE
Feature: Autogenierierte Häuser

### ISSUE THREAD

**Issue by CsharpLassi** [OctoAwesome/octoawesome#174]
ich muss hier einfach mal mein neues Feature vorstellen, mit ein bissel glück ist es bis Donnerstag fertig.

![hauser_1](https://cloud.githubusercontent.com/assets/12987399/19040917/5f441c7a-8986-11e6-9d11-ce0ec6859297.png)

**Comment by CsharpLassi** [comment]
In dem Atemzug müssen wir auch was nochmal an der Architektur machen das ist ja undurchsichtig, wenn man mal ein paar Komponeten einfügen will

**Comment by tomwendel** [comment]
Ich stimme zu :D

Tiny Keyboard, tiny Message
________________________________
Von: CsharpLassi<mailto:notifications@github.com>
Gesendet: ‎03.‎10.‎2016 17:15
An: OctoAwesome/octoawesome<mailto:octoawesome@noreply.github.com>
Betreff: Re: [OctoAwesome/octoawesome] Feature: Autogenierierte Häuser (#174)


In dem Atemzug müssen wir auch was nochmal an der Architektur machen das ist ja undurchsichtig, wenn man mal ein paar Komponeten einfügen will

**Comment by CsharpLassi** [comment]
Äh wollt ich ja Antworten.
Das Problem ist die Häuser im Code zu definieren so ein bissel Mist ist und im Texteditor wird es nicht besser.
Meine Idee war das mit einer Tastenkombination eine Bauplattform zu erstellen wo man dann die Struktur bauen kann und die dann serialisiert wird. Mein Problem war nur als erstes von extern die Tastenbindung zu implementieren, weil das geht nur im Client. 
Dann wollte ich eine Klasse implementieren die die Plattform in die Welt erstellt. Die Klasse sollte direkt in die Runtime rein, weil ich es dort für Sinvoll erachte. geht aber nicht weil ich keinen Direkten zugriff auf auf die Blockdefinitions hab zum Bauen. Dann hab ich es versucht in Basic zu implementieren dort hab ich aber kein zugriff auf den Ressourcemanager. Wenn ich das ganze in eine eigene Dll auslagere als Plugin, kann ich kein Keybindings hinzufügen.

Das Problem ist nur das das z.B. eine "Gottkomponente" ist die einfach so die Welt verändern kann.
