### ISSUE TITLE
Kommentare ändern

### ISSUE THREAD

**Issue by CsharpLassi** [OctoAwesome/octoawesome#186]
Hallo, irgendwie müssten wir mal alle Kommentare (Klassen, Methoden,...) ins Englische Übersetzen oder die wenigen Englischen ins deutsche.
Das geht ja garnnicht mehr.

**Comment by ManuelHu** [comment]
Ich wäre für einheitlich Deutsch, alle anderen Projektseiten sinds ja auch. Englische Doku hilft auch niemandem wenn man den Rest nicht versteht.

**Comment by jvbsl** [comment]
Und ich wär für umgekehrt, damit die, die sonst alles andere in Deutsch lesen und eben nicht verstehen können wenigstens mit der Doku die Chance haben. Außerdem hat man dann ein breiteres Personenspektrum. Und Code ist immer Englisch. Wer nicht gut genug Englisch kann um den Code zu verstehen ist entweder noch ziemlich Jung(oder verdammt schlecht in Englisch), bzw. einfach noch zu schlecht im Coden, bei was Deutsche Kommentare dann auch nicht mehr helfen.

**Comment by tomwendel** [comment]
Ich mache ja alle meine Lernprojekte explizit auf deutsch, weil ich der Meinung bin, dass a) es schon genug Zeug auf englisch gibt und b) ich schlichtweg ein besseres Programm in meiner Muttersprache liefern kann. Natürlich erreicht man auf englisch mehr, aber fraglich ist, ob das die Zielsetzung ist. Code mag üblicherweise englisch sein, kurze Kommentare und Commits meinetwegen auch noch. Aber wiki und Dokumentation werde ich nicht in einer Fremdsprache führen.

Tiny Keyboard, tiny Message
________________________________
Von: jvbsl<mailto:notifications@github.com>
Gesendet: ‎10.‎12.‎2016 14:38
An: OctoAwesome/octoawesome<mailto:octoawesome@noreply.github.com>
Betreff: Re: [OctoAwesome/octoawesome] Kommentare ändern (#186)


Und ich wär für umgekehrt, damit die, die sonst alles andere in Deutsch lesen und eben nicht verstehen können wenigstens mit der Doku die Chance haben. Außerdem hat man dann ein breiteres Personenspektrum. Und Code ist immer Englisch. Wer nicht gut genug Englisch kann um den Code zu verstehen ist entweder noch ziemlich Jung(oder verdammt schlecht in Englisch), bzw. einfach noch zu schlecht im Coden, bei was Deutsche Kommentare dann auch nicht mehr helfen.

**Comment by jvbsl** [comment]
Vlt. reden wir von was unterschiedlichem aber Doku ist für mich das auto generierte Zeug aus den Kommentaren.

**Comment by tomwendel** [comment]
Viel mehr technische Doku gibts ja eh nicht. Aber aus dem Grund hatte ich ja deutsch angefangen. Muss manuel aber recht geben. Mix ist auch doof

Tiny Keyboard, tiny Message
________________________________
Von: jvbsl<mailto:notifications@github.com>
Gesendet: ‎10.‎12.‎2016 15:36
An: OctoAwesome/octoawesome<mailto:octoawesome@noreply.github.com>
Cc: Tom Wendel<mailto:tom.wendel@rabbitcode.de>; Comment<mailto:comment@noreply.github.com>
Betreff: Re: [OctoAwesome/octoawesome] Kommentare ändern (#186)


Vlt. reden wir von was unterschiedlichem aber Doku ist für mich das auto generierte Zeug aus den Kommentaren.

**Comment by ManuelHu** [comment]
Der Großteil der bestehenden Doku-Kommentare sind sowieso auf Deutsch, die paar englischen in Deutsch zu übersetzen wäre auch weniger Arbeit als umgekehrt.

**Comment by Gallimathias** [comment]
Wir machen einfach multilanguage sowohl vs als auch sandcastle unterstüzen das, das wiki bleibt deutsch und problem gelöst

**Comment by tomwendel** [comment]
Interessanter Ansatz. Wie macht VS das eigentlich? Nie gemacht

Tiny Keyboard, tiny Message
________________________________
Von: Gallimathias<mailto:notifications@github.com>
Gesendet: ‎10.‎12.‎2016 17:54
An: OctoAwesome/octoawesome<mailto:octoawesome@noreply.github.com>
Cc: Tom Wendel<mailto:tom.wendel@rabbitcode.de>; Comment<mailto:comment@noreply.github.com>
Betreff: Re: [OctoAwesome/octoawesome] Kommentare ändern (#186)


Wir machen einfach multilanguage sowohl vs als auch sandcastle unterstüzen das, das wiki bleibt deutsch und problem gelöst

**Comment by Gallimathias** [comment]
```
/// <summary>
/// Gets or sets the fill size of the load operation.
/// </summary>
/// <summary xml:lang="fr">
/// Obtient ou définit la taille de remplissage de l'opération de chargement.
/// </summary>
/// <summary xml:lang="de">
/// Ruft die Größe des Ladevorgangs ab oder legt diese fest.
/// </summary>
```

**Comment by ManuelHu** [comment]
Wir benutzen kein sandcastle mehr. Bei docfx hätte ich noch nichts dazu gesehen. (ist natürlich auch noch so halb "beta", bei jedem Release kommen ein paar Funktionen dazu). Ich finde, dass das dann zu viel wird für inline im Code, irgendwann haben wir mehr Kommentar als Code ;-)

**Comment by Gallimathias** [comment]
Ok wusste ich nicht. Ja das wird viel, aber mann kann ja die summarys einklappen, kein problem also. Das beispiel ist ja jetzt dreisprachig in unserem fall ist es zweisprachig und außerdem sollst du in den summarys keine Romane schreiben ;)

**Comment by ManuelHu** [comment]
Also grad geprüft, docfx kann definitiv keine Mehrsprachige Doku (zumindest nicht einfach so eintragen und es läuft, wie in Sandcastle). Auch die strings in den Templates sind hardcoded Englisch, was nicht unbedingt auf die besten Lokalisierungsmöglichkeiten hindeutet ;-) Sandcastle schreibt die Sprachen einfach untereinander, docfx zeigt nur die summary ohne xml:lang.
![docfx](https://cloud.githubusercontent.com/assets/10050780/21075250/168638a8-bf0d-11e6-8658-03f2b13a7c97.png)
![sandcastle](https://cloud.githubusercontent.com/assets/10050780/21075254/1f713742-bf0d-11e6-91a7-606690e11631.png)

**Comment by Gallimathias** [comment]
Man kann auch irgendwie zwei verschiedene xml dokus erstellen lassen dann müssten doch auch zwei dokus am ende rauspurzeln oder?

**Comment by ManuelHu** [comment]
DocFX verwendet soweit ich weiß nicht die von VS generierten XML-Dateien sondern extrahiert die Kommentare selbst aus dem Code.

**Comment by CsharpLassi** [comment]
Also haben wir uns jetzt auf was geeinigt?

Also Code auf Englisch ist ja kein Thema. Aber ich muss zugeben das ich Kommentare lieber auf Deutsch hätte, weil es doch das Verständnis etwas verstärkt und bis jetzt sind wir ja eine reine deutschsprachige Community. Wenn es aber eine schöne Methode gibt zweisprachig das ganze zu machen bin ich auch dafür.

**Comment by ManuelHu** [comment]
Julian als einziger hat bisher explizit für Englisch gestimmt. Tom, Du und ich wollen es auf Deutsch.
Maximilian und Du haben auch noch multilanguage vorgeschlagen, was aber mit dem zur Zeit verwendeten Tool (noch) nicht möglich ist, Issues dazu gibts aber seit fast einem ganzen Jahr.

Code auf Englisch ist klar.

**Comment by tomwendel** [comment]
Ich schließe mich Lassi an. Code englisch, Docu deutsch. Selbst wenn es multilanguage gäbe, müsste das auch jemand pflegen...

Tiny Keyboard, tiny Message
________________________________
Von: Manuel Huber<mailto:notifications@github.com>
Gesendet: ‎11.‎12.‎2016 11:12
An: OctoAwesome/octoawesome<mailto:octoawesome@noreply.github.com>
Cc: Tom Wendel<mailto:tom.wendel@rabbitcode.de>; Comment<mailto:comment@noreply.github.com>
Betreff: Re: [OctoAwesome/octoawesome] Kommentare ändern (#186)


Julian als einziger hat bisher explizit für Englisch gestimmt. Tom, Du und ich wollen es auf Deutsch.
Maximilian und Du haben auch noch multilanguage vorgeschlagen, was aber mit dem zur Zeit verwendeten Tool (noch) nicht möglich ist, Issues dazu gibts aber seit fast einem ganzen Jahr.

Code auf Englisch ist klar.

**Comment by reicheltp** [comment]
IMHO: Code auf Englisch. Kommentar auf English. Git Messages auf Englisch. Doku auf Englisch. 

Finde es sehr merkwürdig, wenn man deutsche Kommentare liest und aber alle Klassen / Verweise etc. auf Englisch sind. Wo zieht man den klaren Strich um zu unterscheiden, was man jetzt auf Deutsch oder Englisch schreibt? Oder wollt ihr alles Alles Deutsch schreiben auf `see/seealso` verzichten und es unmöglich machen die entsprechenden Klassen zu finden?

**Comment by reicheltp** [comment]
Wer die Dokumentation auf Deutsch will, weil er kein Englisch kann, soll halt Google Translator benutzen. 😝

**Comment by tomwendel** [comment]
Gleich dieser vorwurfsvolle Ton…?! Jetzt hör mal… :D
Ich sehe jetzt keinen Grund warum im Kommentar nicht „Um den Nippel durch die Lasche zu ziehen nutzen wir <see href=“AwesomeClass“>“ stehen sollte. Die Klasse hat nun mal einen englischen Namen und kann doch ohne Probleme so angesprochen werden. Aus meiner Sicht spricht auch nichts dagegen das in weiterführender Dokumentation so zu handhaben.

Also um das noch mal auf den Punkt zu bringen: Mag sein, dass es gängige Praxis ist bei Open Source Projekten alles auf Englisch zu machen. Aber wir sind kein normales Dev-Projekt sondern ein Lernprojekt  – mit einer ausschließlich deutschen Community. Die Diskussion habe ich bei AntMe! leider schon viel zu oft geführt und dort auch immer wieder auf die Erkenntnis gekommen, dass es schlichtweg für jeden Lernenden einfacher ist Dinge in seiner Muttersprache zu lesen/hören. Und wer jetzt mit der elitären „aber wer kein Englisch kann, braucht auch nicht zu programmieren“ Einstellung ankommt, der kann Heim gehen. Ich mache jetzt Schulungen für Einsteiger seit  fast 10 Jahren und bin damit sehr gut gefahren.

Mal ganz davon abgesehen gibt’s eh schon viel zu viel Material in Englisch. Wer den elitären Weg gehen will, soll sich dort schlau machen. Meine Zielsetzung war es von Anfang an was für deutschsprachige Einsteiger zu machen. Und es liegt nicht in unserem Interesse (zumindest spreche ich da für mich) auf Biegen und Brechen die Reichweite zu vergrößern.

Mir scheint jemand muss hier mal ein Statement setzen. Das tue ich jetzt: Englischer Code (Klassennamen, Properties, Variablen), Deutsche Kommentare (Summaries, Inline Kommentare, Commits). Ich hatte es die letzten Male anders versucht, aber Manuel hat vollkommen Recht damit, dass dieses Durcheinander niemandem hilft.

Von: Paul Reichelt [mailto:notifications@github.com]
Gesendet: Sonntag, 11. Dezember 2016 11:33
An: OctoAwesome/octoawesome
Cc: Tom Wendel; Comment
Betreff: Re: [OctoAwesome/octoawesome] Kommentare ändern (#186)


IMHO: Code auf Englisch. Kommentar auf English. Git Messages auf Englisch. Doku auf Englisch.

Finde es sehr merkwürdig, wenn man deutsche Kommentare liest und aber alle Klassen / Verweise etc. auf Englisch sind. Wo zieht man den klaren Strich um zu unterscheiden, was man jetzt auf Deutsch oder Englisch schreibt? Oder wollt ihr alles Alles Deutsch schreiben auf see/seealso verzichten und es unmöglich machen die entsprechenden Klassen zu finden?

**Comment by jvbsl** [comment]
Ausschließlich Duetsche Community stimmt aber auch nicht ganz, es waren immer wieder viele Englisch sprachige im Stream, Ich erinner mich auch an einige die ich regelmäßig gesehen habe, die haben sich nur im Stream nie wirklich viel gemeldet. Und richtig einsteigen in die Community ist für die natürlich auch besonders schwer.
Also ich bin in dem Fall auch für Mehrsprachig, halte ich hier für die einzig sinnvolle Lösung, sonst gibts hier nur Streit :D

**Comment by ManuelHu** [comment]
Mehrsprachig geht aber (noch) nicht mit docfx und obs dann genauso geht wie in sandcastle ist dann die Frage.

**Comment by tomwendel** [comment]
Du meinst alle würden mit dir streiten? :-D
Gegen Multilanguage spricht aktuell

a)      Tools supporten das nicht

b)      Doppelter Aufwand (mit xml:lang schnickschnack sogar dreifacher) und wir kommentieren ja jetzt schon kaum

Und was internationales Publikum angeht: Hauptinfo ist der Stream und der ist deutsch. Und warum gilt das google translator argument nicht auch umgekehrt?

Von: jvbsl [mailto:notifications@github.com]
Gesendet: Sonntag, 11. Dezember 2016 14:47
An: OctoAwesome/octoawesome
Cc: Tom Wendel; Comment
Betreff: Re: [OctoAwesome/octoawesome] Kommentare ändern (#186)


Ausschließlich Duetsche Community stimmt aber auch nicht ganz, es waren immer wieder viele Englisch sprachige im Stream, Ich erinner mich auch an einige die ich regelmäßig gesehen habe, die haben sich nur im Stream nie wirklich viel gemeldet. Und richtig einsteigen in die Community ist für die natürlich auch besonders schwer.
Also ich bin in dem Fall auch für Mehrsprachig, halte ich hier für die einzig sinnvolle Lösung, sonst gibts hier nur Streit :D

**Comment by jvbsl** [comment]
Nene, jetzt ist ja noch kein Streit, kommt aber vlt. noch^^

zu a) Ja das wär dann natürlich vorraussetzung
zu b) es findet sich schon nen Depp, der das macht^^(aber 3facher Aufwand ists bei 2 Sprachen nicht)

Und Google Translate kommt ja kaum mit Englisch klar, wie soll er da mit Deutsch klarkommen? :D

**Comment by tomwendel** [comment]
Also nicht falsch verstehen. Mutli-Language wäre wirklich cool. Ich sehe das nur nicht als praktikabel.
Dreifacher Aufwand deshalb, weil VS mir Standardmäßig die Summary baut wenn ich drei Slashes eingebe. Wenn ich jetzt zwei Stück mit jeweils Language-Attributen haben will, kommt da schon etwas mehr Tipp-Aufwand – daher rührt mein Argument.

Von: jvbsl [mailto:notifications@github.com]
Gesendet: Sonntag, 11. Dezember 2016 15:13
An: OctoAwesome/octoawesome
Cc: Tom Wendel; Comment
Betreff: Re: [OctoAwesome/octoawesome] Kommentare ändern (#186)


Nene, jetzt ist ja noch kein Streit, kommt aber vlt. noch^^

zu a) Ja das wär dann natürlich vorraussetzung
zu b) es findet sich schon nen Depp, der das macht^^(aber 3facher Aufwand ists bei 2 Sprachen nicht)

Und Google Translate kommt ja kaum mit Englisch klar, wie soll er da mit Deutsch klarkommen? :D

**Comment by reicheltp** [comment]
@tomwendel Das sollte gar nicht vorwurfsvoll klingen :D 

Multilang ist schmarn. Das Tooling ist scheiße. Und absolut unüblich. Wenn man es freundlich für andere machen möchte kann man ja auch ein Sprachenbutton hinzufügen der die Docs in einen Translater haut. Selbst MS hat ihre kompletten Docs auf Englisch und lässt die ganze Sprachvariationen mitlerweile mit Bing generieren.

Bei einer Highlevel Docu stimm ich voll und ganz zu, dass es dort einem muttersprachler deutlich einfacher fällt sich einzuarbeiten. 
Bei Low Level Docu wie Kommentare am Code und Summary finde ich es schwierig, und sehe eher einen Nachteil, da immer ein Denglish das Ergebnis ist. Außerdem handelt es sich um simple Beschreibungen wie `Event to observe the application state.` ob man dass wirklich in etwas wie: `Ereigniss zum Überwachen des Anwendungszustandes` übersetzen muss, finde ich fragwürdig. Schließlich handelt es sich meistens um übliche Fachbegriffe, deren Übersetzung ins Deutsche manchmal merkwürdig ist. Gerade wo `event` das Keyword (sollte ich jetzt Schlüsselwort sagen?!) ist, und `_applicationState` mitunter die Variable ist, welche man überwacht.

HighLevel Doku (wiki) + Videos + Issues auf Deutsch und Code / Comments / Git auf Englisch ist meiner Meinung nach ein guter Weg um Neulinge an Software Development heran zu führen. Denn die Englischkentnisse der Anfänger vom Heute sind dank dem Internet / Digitalisierung bei weitem besser als derer von vor  Jahren. Zusätzlich kann jemand mit Deutsch als Fremdsprache, welcher vielleicht mit der Doku / Tutorial mehr Schwierigkeiten hat, dennoch auch den Code verstehen.

**Comment by Gallimathias** [comment]
Also HighLevel Doku steht glaube ich nicht zur Disposition, die Sollte und Muss deutsch.

Ich wäre wie gesagt auch weiter für Multilanguage auch wenn es mehr aufwand bedeutet.

Wie wäre es wenn wir sagen primär alles auf Deutsch und wenn jemand muse hatt **ergänzt** er dann um Englisch und zack schon sind wir zweitsprachig. Egal ob das ein tool kann oder nicht.

**Comment by CsharpLassi** [comment]
Also zum automatischen Übersetzen, muss ich ja sagen das msdn da ja wirklich mittlerweile Top ist.

Ich glaub die Diskussion geht auch mittlerweile es was weiter, als geplant. Das Wiki, Videos, Issues, Streams sollten auf Deutsch bzw mehrsprachig bleiben.

Es geht mir nur um die Zusammenfassungen im Code. Mir ist Deutsch oder Englisch egal, weil sie meistens eh sehr einfach gehalten sind und der Name sagt ja oft schon alles aus. Wir sollten nur festlegen und bis jetzt ist die Meinung immer noch zwei geteilt.

**Comment by CsharpLassi** [comment]
So damit mir vorwärts kommen.

http://strawpoll.de/42g671x

Bitte jeder nur einmal. Ich würde auch alles Runden um den Code zusammenlegen und betrifft die Primate Sprache.

**Comment by fnawratil** [comment]
Auch wenn das hier schon zwei Wochen alt ist will ich auch noch meinen Senf dazugeben.

Ich bin ebenfalls dafür, dass die Kommentare auf Englisch sind, und zwar nicht nur wegen "Conventions" etc. sondern auch, weil OctoAwesome das Vorzeigeprojekt für Engenious und MonogameUI ist und wir nicht wissen was sich daraus noch entwickelt.

Grüße,
rave

**Comment by ManuelHu** [comment]
Natürlich ist OctoAwesome eine Art Vorzeigeprojekt dafür, der aber mit MonoGameUi bzw. engenious arbeitende Client ist gar nicht in die Dokumentation eingeschlossen; die API-Doku eines eigenen Screens wäre z.B. nicht relevant, da sie ja die gleichen Methoden usw. hat wie die Elternklasse. Die (noch unveröffentlichte) MonoGameUi Doku darf aber gern englisch werden.

**Comment by Gallimathias** [comment]
Wie hatten wir uns jetzt hier entschieden?

**Comment by ManuelHu** [comment]
Noch gar nicht. Stand ist immer noch: Fast alle Kommentare bisher auf Deutsch, nur weniges auf Englisch. Multilanguage geht mit docxf (auch über ein Jahr später) noch nicht, es gibt anscheinend auch keine Bestrebungen das einzubauen.

Es gibt die beiden Standpunkte
* Deutsch, weil a) alles andere (Streams, Wiki, Videos) auf Deutsch ist und man das Projekt nur mit der spärlichen Code-Dokumentation auf Englisch auch kaum für nicht-deutschsprachige verständlich machen kann. b) Ist-Zustand, weniger Aufwand c) deutschsprachiges Lernprojekt (vgl. @tomwendel)
* Englisch, weil a) alle es so machen/die Namen im Code Englisch sind und sonst Denglisch entsteht und b) um den Einstieg zu erleichtern.

Beide Standpunkte haben jeweils 3 Unterstützer (in diesem Thread) - Eine weitere Diskussion hier erachte ich nicht als sinnvoll. Tom hat als "[BDFL](https://de.wikipedia.org/wiki/Benevolent_Dictator_for_Life)" damals die Diskussion mit der Entscheidung für Deutsch beendet.

**Comment by Gallimathias** [comment]
Den begriff kannte ich noch garnicht :D 

Ich denke entweder aktzeptieren wir die Aussage von Tom oder wir lassen es darauf beruhen und die Diskussion flammt rund um das Thema StyleGuide wieder auf.

**Comment by fnawratil** [comment]
Eine neue Umfrage: https://strawpoll.de/cw18ea7

Vielleicht kommen wir ja diesmal zu einem Ergebnis...

**Comment by tomwendel** [comment]
Viel wichtiger wäre eine Strawpoll die endgültig darüber abstimmt, ob das Ergebnis der 100sten Strawpoll zu diesem Thema nun tatsächlich akzeptiert wird, auch wenn ein weiteres mal das unerwünschte Ergebnis "Deutsch" dabei heraus kommt - so wie jedes mal bisher.

Außerdem halte ich "weil alle es so machen" für das falscheste Argument für Englisch. Einen schnellen Einstieg ins Projekt sehe ich damit auch nicht, da der Rest der Doku eben deutschsprachig ist. Aber das hatten wir schon 1000 mal.

**Comment by fnawratil** [comment]
@tomwendel Die letzte Strawpoll lieferte ein unentschieden... Deswegen hier eine Neue...
Wie hatten außerdem im TS noch drüber diskutiert

**Comment by tomwendel** [comment]
Dann beantrage ich hiermit, dass auch der Stream auf englisch moderiert wird - für den einfacheren Einstieg ;)

**Comment by susch19** [comment]
Hätte nichts gegen englische Moderation, aber dazu können wir Marcus nicht überreden

**Comment by tomwendel** [comment]
Ganz einfach: Fork, nenn es NovemAwesome und ab gehts!

**Comment by fnawratil** [comment]
@tomwendel Siehst du das hier jetzt als persönlichen Angriff oder was geht hier ab?

Ich wollte doch nur mal fragen um endlich mal auf was zu kommen. ;)
(Die Strawpoll und bisherige Diskussion endeten ja bisher immer ohne Ergebnis.)

Momentan haben wir nämlich viele mixed-Kommentare und das ist auch nicht wirklich schön...

LG, rave

**Comment by tomwendel** [comment]
Hi Rave,

nein, nicht angegriffen. Mich nervt nur dieses ewige hin und her und die immer wieder kehrende Diskussion darum - so geht's dir ja auch. Und ich erinnere mich, dass wir das 1000 mal im Stream angesprochen haben und im Ergebnis immer wieder bei Deutsch gelandet sind. Wie eben der wohlwollende Diktator es seit Tag 1 handhaben wollte. Es ist ein deutscher Stream, ein deutsches Lernprojekt und ich sehe bis zum heutigen Tag keinen Mehrwert in englischen Kommentaren.

Sollte sich die Mehrheit aber dafür entscheiden, ist das ok für mich. Aber entscheidet endlich mal.

**Comment by tomwendel** [comment]
Ich hab den Link zur Strawpoll übrigens geteilt. Das waren keine Bots.

**Comment by fnawratil** [comment]
@tomwendel Ok, ich dachte nur, dass wir gar icht so viele Contributors auf GitHub haben ^^

**Comment by tomwendel** [comment]
Dachte mir ich binde mal den Konsumenten mit ein

**Comment by fnawratil** [comment]
@tomwendel Danke übrigens fürs nutzlos-machen dieser Umfrage... ;)

Ich hatte eigentlich gehofft, das endlich mal "demokratisch" zu klären, aber jetzt geb ich's auch langsam auf...

Grüß, rave

**Comment by tomwendel** [comment]
Also um das hier mal abzuschließen (vermutlich nicht der richtige Platz, aber passt gerade):

Ich bin sehr froh, dass ihr euch dem Projekt annimmt und es hier endlich konsequent und mit geballter Macht weiter geht. Dass ich keine Zeit mehr dafür aufbringen kann finde ich sehr bedauerlich und ich sehe leider auch für die Zukunft wenig Chancen mich mit der selben Energie einzubringen wie das bei den ersten 500 Folgen der Fall war. Umso glücklicher bin ich, dass es weiter geht. Es leeeebt also! :) Ich danke euch sehr dafür.

Dementsprechend geht das Ganze natürlich jetzt auch in eine entsprechend andere Richtung mit anderer Zielsetzung, anderem Tempo und anderen Schwerpunkten. Daran muss ich mich jetzt wohl gewöhnen. Dennoch nehmt ihr ja gerne Referenz auf Dinge, die ich Anfangs mal so für die Serie festgelegt habe und das ist auch toll so. Da gab es nämlich ein paar Grundregeln an die ich mich erinnere und auf die ich in diesem Zusammenhang verweisen möchte. 

- **Das Projekt ist deutschsprachig.** Stream auf deutsch, deutsche Texte, deutsche Doku also effektiv deutsche Lernsprache. Dass der Quellcode englisch ist, ist schlichtweg dem Sprachdesign geschuldet.

- **Alles passiert on Screen** - sogar das googeln nach der Lösung. Ein Thema, das mich gerade nach Ende meiner Stream Zeit durchaus beschäftigt hat. Die Idee, dass alles (zumindest wichtige einschneidende Dinge) per Stream oder Video nachvollziehbar gemacht werden soll. Ganz besonders schwer getroffen hat mich da dieser radikale "wir parallelisieren mal eben" Change vom grünen Schaf getroffen. Hauptsache kryptisch, Hauptsache ignorieren warum wir diese Designentscheidung früher getroffen haben und vor allem: kaputt gemacht. Und das alles offscreen. :(

- **Es handelt sich um eine Spielwiese, nicht um ein Tutorial**. Das hat zur Folge, dass Dinge nicht perfekt gelöst sind, aber nun mal funktionieren. Aber gerade im späteren Verlauf gab es oft den Moment  an dem ich mir anhören musste wie dumm doch meine Entscheidungen gewesen sind. Da kommt dann jemand, der das Projekt gerade mal eine Woche kennt, unreflektiert das implementiert was Minecraft an dieser Stelle macht und wir haben alle nichts dabei gelernt. Ganz zu schweigen vom WCF gebashe. Mag sein, dass ihr Profis alle schon die bessere Lösung kennt. Aber dennoch demonstiert WCF recht gut die konzeptionellen Zusammenhänge von RPCs. Ich möchte diesen Umweg nicht missen.

Viel mehr Grundregeln des freundlichen Diktators fallen mir dazu eigentlich auch nicht ein und es wäre mir ein Fest, das auch weiterhin so verfolgt zu sehen. Schließlich handelt es sich um die Grundpfeiler des Formats.

Beste Grüße und Ruhe jetzt von meiner Seite
Tom

Und nein. Die Umfrage ist nicht nutzlos.

**Comment by CsharpLassi** [comment]
Sollt jetzt glaub ich genug Behandelt wurden sein.
