### ISSUE TITLE
Wie weit soll der Entity-Branch gehen und was kommt dannach??

### ISSUE THREAD

**Issue by CsharpLassi** [OctoAwesome/octoawesome#187]
Hallöle ich mal wieder,

mal noch eine Andere Frage wie viel wollen wir noch im Entity-Branch machen.
Also bis jetzt sind wir auf das Komponenten-Model umgestiegen und alle alten Funktionen wurden neu implementiert. Also nächstes müsste alles Rund um den Actorhost noch aufgeräumt werden, aber dann ist der Teil fertig.

Meine Frage ist was soll noch rein bevor wir das mit den Develop-Branch mergen nicht das wir wieder eine Leiche mehr drinne haben. Wir haben auch ne Apfel-Entity implementiert die nichts macht und auch nicht angezeigt werden kann.
Sonst würd ich sagen aufräumen und mergen. Wer soll das machen ???

Andere Frage was sollte man danach Anfangen. Ich würd ja sagen wir sollten den Wauzi wieder ins Bot holen, aber das ist ein Aufwand ...

viele grüße
Lassi

**Comment by CsharpLassi** [comment]
Stimmt das serialisieren hab ich jetzt doch glatt vergessen.

**Comment by ManuelHu** [comment]
Wir haben den Entity-Branch mittlerweile in den develop gemerged.
