### ISSUE TITLE
Wie geht es weiter?

### ISSUE THREAD

**Issue by fnawratil** [OctoAwesome/octoawesome#191]
Ich stell hier einfach mal frech die Frage rein, wie es denn mit OctoAwesome weitergehen soll?

Mir ist klar, dass Tom momentan weniger Zeit/Lust hat, deswegen auch an alle anderen: Sind Streams geplant/gewünscht?

Grüße,
rave

**Comment by ManuelHu** [comment]
Ich würde bei den Streams auf jeden Fall zuschauen. Zum selber Streamen fehlt mir leider das Equipment und eine gute Internetverbindung.

Natürlich könnte man auch ohne Stream "einfach so" entwickeln (so wie das 99% aller "normalen" Projekte tun), aber das hat dann nicht so den Reiz. Vielen geht dann wohl das Erklären/Lernen ab (bzw. sie können sich gar nicht direkt einbringen, weil sie C# nicht können). Das ist auch nicht mein Favorit, aber wenn sich niemand findet, lieber so als das Projekt sterben zu lassen.

**Comment by HendrikFW** [comment]
Für neue Streams wäre ich auch zu haben. Ich hab das Projekt zwar, mangels Zeit, in diesem Jahr nich nicht großartig verfolgt aber ich würde mich freuen wenn wir wieder Streams auf die Beine stellen könnten. Ich steck zwar nicht so wirklihc in dem Code drinn aber hab immer gern zugeschaut.

**Comment by ManuelHu** [comment]
So es geht jetzt weiter ;-) Für Informationen die Webseite/Wiki konsultieren.
