### ISSUE TITLE
Blockdefinitions zusammenfassen

### ISSUE THREAD

**Issue by fnawratil** [OctoAwesome/octoawesome#196]

**Comment by Gallimathias** [comment]
Bitte beschreibung ergänzen @fnawratil

**Comment by CsharpLassi** [comment]
Die Blockdefinitions sollten vereinheitlicht werden oder generischer werden. Eventuell durch Definitionsdatein, aber nicht immer durch Klassen.

**Comment by HierGibtEsDrachen** [comment]
Gehört hier vllt. nicht recht rein aber was haltet ihr von einer XML basierten Initialisierung der Extensions.
Das würde dann so ähnlich aussehen wie der XAML Code von WPF :)

**Comment by ManuelHu** [comment]
@HierGibtEsDrachen Schau mal in #216, da geht's mehr in diese Richtung. Da sind auch schon einige Argumente pro/contra gefallen.

**Comment by Gallimathias** [comment]
Ich denke das das Thema mit #216 gut bedient ist. Bitte weitere anmerkungen hierzu dort vermerken oder bei bedarf ein spezifischeres Issue aufmachen.
