### ISSUE TITLE
CleanUp der BlockDefinition mehr Generisch

### ISSUE THREAD

**Issue by Gallimathias** [OctoAwesome/octoawesome#209]
Reduntanden Code verhindern, mehr generic.
Idee Statt diesen Zirkus
Macht das doch auf ein Enum für alle Seiten für das Solid Dann ist es nur eine Funktion die virtual ist und 6 die nur checken ob ein flag gesetzt ist Genauso für die Texturen, mach ein Array 6 Einträge, fertig.

Für die Seitenflächentexturen, das ist halt übelst virtual und macht es nur schwieriger

**Comment by Gallimathias** [comment]
Anmerkung aus dem Stream:
if(das mit dem Cleanup so stattfindet ){
Ihr seid die besten! Die tollsten Programmier der Welt! Die Helden des Softwarealltags! Die leuchtenden Vorbilder für die nächste Generation an Entwicklern! Kurz: Die tollsten Menschen der Welt!
}

**Comment by jvbsl** [comment]
Sind aber nicht alles einfache blöcke, außerdem finde ich sollten das am ende auch nur ids sein. Am besten für TextureArrays

**Comment by Gallimathias** [comment]
fixed with 8df47f1
