### ISSUE TITLE
Chunkränder werden nicht aktualisiert

### ISSUE THREAD

**Issue by tomwendel** [OctoAwesome/octoawesome#21]
Submit von Manuel:

Eine unserer Optimierungen war die weitsichtigere Verarbeitung von Nachbarchunks um herauszufinden, ob Chunkränder gezeichnet werden müssen oder nicht. Das funktioniert auch solange bis der Block, der für das nicht-rendern zuständig war, im Nachbar-Chunk entfernt wird.

Zwar wird der Chunk, in dem Veränderungen verursacht werden, neu erstellt, nicht jedoch der Nachbar-Chunk auf den das evtl. auch Auswirkungen hat. Dadurch kommt es zu Löchern im Boden wenn Blöcke an Chunkgrenzen entfernt werden.

![screenshot](https://cloud.githubusercontent.com/assets/2411364/10145856/f67ece3a-6625-11e5-9d5e-9479b2d66bfb.JPG)

**Comment by jvbsl** [comment]
https://github.com/OctoAwesome/octoawesome/tree/feature/renderfix
sollte das ganze fixen. Evtl. andere Herangehensweise für inkrementelles Update.
Zusätzlich flackern tritt immer noch manchmal auf(Zeichnen während verändern der Daten).
