### ISSUE TITLE
Entladen des Spiels implementieren

### ISSUE THREAD

**Issue by ManuelHu** [OctoAwesome/octoawesome#211]
https://github.com/OctoAwesome/octoawesome/blob/daa813ad0be3f22ff9f0f30ed43c06bb2d03d4b1/OctoAwesome/OctoAwesome.Runtime/ResourceManager.cs#L109-L118

Das ist der Grund, warum das zuletzt gespielte Universum im Auswahlbildschirm nicht augewählt werden kann (ist @Gallimathias im Stream aufgefallen)

**Comment by Gallimathias** [comment]
Noch mehr zu tuhen :D

**Comment by Gallimathias** [comment]
fixed with 665ef9b
