### ISSUE TITLE
Planets im Universe speichern

### ISSUE THREAD

**Issue by ManuelHu** [OctoAwesome/octoawesome#212]
Aus dem Stream vom 21.12.2017

**Comment by Gallimathias** [comment]
Aktuell sind die Planeten vom Universum entkoppelt im Resourcen Manager vorhanden. Rein vom Entititäten Modell sollten allerdings die Planeten Teil des Universums sein.

@tomwendel hatte einwände bezüglich der Verlagerung der Planeten in die universums klasse.

Ich bin für ein klares entitäten Modell, die frage wäre allerdings welchen Aufwand das bedeutet und ich würde gerne nochmal die Einwände aus dem Stream erörtern

**Comment by tomwendel** [comment]
Ich sags gerne nochmal: Das macht keinen Sinn! Die Planeten sind deshalb im ResManger weil dessen Aufgabe das dynamische laden und entladen nach Bedarf darstellt. Mag ja sein, dass das Modell hübscher wäre, wenn das Universum eine Liste von Planeten hielte, aber das ist in unserem Fall höchst unpraktikabel. ...aus dem selben Grund warum auch die Chunks nicht im Planeten gespeichert werden. Das wäre nämlich nach dieser Argumentation der nächste logische Schritt.

Indem man diese 3 ebenen referenziell voneinander trennt ist das vollkommen dynamische Erstellen/Löschen/Speichern/Laden von Fragmenten möglich ohne jedes mal die nächsthöhere Verwaltungseinheit mit einzubeziehen.

**Comment by CsharpLassi** [comment]
Ah jetzt versteh ich das.

Ich stimme @tomwendel zu, besonders weil man sich das Universum nicht so vorstellen sollte wie man das sich gewohnt ist.

**Comment by CsharpLassi** [comment]
So ich glaub das war auch geklärt.

Planeten bleiben wo sie sind und werden nicht ausgelagert

**Comment by Gallimathias** [comment]
Ich wollte es mir eigentlich noch detaillierter anschauen und für und wieder abwägen. Ich mache bei bedarf aber dann einfach das Issue wieder auf. Aktuell bleibt der Status so wie er ist.
