### ISSUE TITLE
SimulationComponent "Unschön"

### ISSUE THREAD

**Issue by CsharpLassi** [OctoAwesome/octoawesome#213]
Unschön richtig behandeln

**Comment by Gallimathias** [comment]
@CsharpLassi Es wäre schön wenn du etwas genauer werden würdest bei deinen beschreibungen.

Unschön ist übrigens weder ein gutes Kommentar noch ein besonderst gutes ToDo

**Comment by CsharpLassi** [comment]
Kann ohne Komplettes Redesign nicht gelöst werden
