### ISSUE TITLE
Streaming Format für Colums

### ISSUE THREAD

**Issue by CsharpLassi** [OctoAwesome/octoawesome#215]
Entities werden bei entladen beim Bewegen aus einen Chunk in die entsprechende Chunk-Colum geschrieben.

Das dauert lange, weil der Chunk erst geladen werden muss die Entity hinzugefügt wird und wieder neu gespeichert werden muss. 

Das kann vereinfacht werden wenn Entities einfach angehängt werden können, wenn sie in den Chunk laufen.

**Comment by CsharpLassi** [comment]
Beim Implementieren bitte folgende Diskussion betrachten
#147

**Comment by CsharpLassi** [comment]
#147

**Comment by Gallimathias** [comment]
Wurde durch die Implementierung des "KeyValueStores" quasi gelöst
