### ISSUE TITLE
Ungenutze Variablen entfernen

### ISSUE THREAD

**Issue by Gallimathias** [OctoAwesome/octoawesome#218]
Um Compilerwarnungen zu minimieren und den Code sauberer zu halten sollten nicht genutze Variablen entfernt werden.

 [Trello](https://trello.com/c/1xBpPBpf/102-nicht-verwendete-variablen-entfernen-compiler-warnungen-beheben)

**Comment by CsharpLassi** [comment]
Vielleicht aufpassen bei machen Klassen sind die Variablen schon angelegt, weil sie später gebraucht werden könnten. z.B verschiedene Simulationskomponenten. Eventuell diese nur auskommentieren.

**Comment by Gallimathias** [comment]
Erledigt mit letzten merge in dev
