### ISSUE TITLE
Gravity aus dem Planeten auch verwenden

### ISSUE THREAD

**Issue by ManuelHu** [OctoAwesome/octoawesome#220]
Derzeit haben wir im `Planet` die Gravity, aber nicht im `IPlanet`. Effektiv kann daher die Gravitation nicht verwendet werden (und wird es auch nicht), sollte aber eigentlich zur Berechnung der Physik verwendet werden.

**Comment by CsharpLassi** [comment]
Die Gravity sollte auch abhängig von der generierten Welt sein. Vielleicht sollt ich mich an dem Punkt auch mal in die Allgemeine Relativitätstheorie einarbeiten

**Comment by ManuelHu** [comment]
Na ja, erstmal würde es glaube ich reichen eine Gravitationskonstante pro Planet zu haben - und diese auch zu verwenden. Einfache Systeme mit mehreren Planeten mit unterschiedlicher Gravitation (z.B. Erde - Mond) mit Portalverbindung wären dann bereits möglich.

**Comment by ManuelHu** [comment]
Ich habe jetzt mal einen kleinen Pull Request (#233) erstellt, der in der Berechnung der Gravitationskraft auf die Entity die Gravitationskonstante aus dem Planeten nimmt.

----
@CsharpLassi Zur Berechnung der Gravitationskonstante:

Bei einer angenommenen durchschnittlichen Dichte ähnlich wie bei der Erde (also 5,5*10³ kg/m³) habe ich mal mit dem Netwon'schen Gravitationsgesetz ein wenig rumgerechnet. Da unsere Planeten keine "richtigen" Kugeln sind, gibt es zwei Möglichkeiten:

* Als "Kugelumfang" nimmt man die X-Komponente der Fläche (quasi die "Äquatorlänge").
* Als "Kugeloberfläche" nimmt man die gesamte Planetenfläche (X*Y) und nimmt eine Kugel mit gleich großer Oberfläche an.

Daraus ermittelt man jeweils den Radius, das Volumen, die Planetenmasse und damit die Gravitationskonstante.

Unsere Planeten sind aber viel zu klein - die Werte sind 5*10^-4 m/s² bei der ersten Möglichkeit bzw. 9*10^-4 m/s² bei der zweiten Möglichkeit. Unsere Planeten müssten also für "sinvolle" (d.h. spielbare) Werte viel größer werden!     
(oder: Wir müssten einen zusätzlichen Faktor mit der Dichte multiplizieren - für unsere aktuelle Planetengröße 11111, um auf "Erdniveau" zu kommen. Dann würde bei mehreren unterschiedlich großen Planeten (z.B. Erde - Mond) schon ein Unterschied spürbar sein.

Am besten ist wahrscheinlich eine Mischung aus beidem: Erdgroße Planeten sind meiner Meinung nach für Spiele utopisch (das wären ca. 2^25) Blöcke in jede Richtung!)

**Comment by CsharpLassi** [comment]
@ManuelHu sehr gut

ich denke wir müssen ein Kompromiss finden. Mir wäre es persönlich am liebsten, wenn wir die Gravitationskonstante etwas abändern. So große Planeten sind schon ein Problem, wenn sie überhaupt Möglich wären. 

Also wenn ich das Richtig sehe müsste sie also statt: 6,8*10^-11 m^3/(kg*s^2) so etwas 6,8*10^-7 m^3/(kg*s^2) betragen ??  


Das fänd ich etwas besser, anderes Universum, andere Konstanten. Aus der physikalischen Sicht ist es dann nur noch Fraglich ob sich Planeten und Sterne gebildet hätten.

Also das wäre mein Vorschlag.

**Comment by ManuelHu** [comment]
Ja, genau was anderes hatte ich auch nicht vorgeschlagen ;-) Die Formel lautet `g = 4/3×pi×G×rho×r`, wenn man die Spielermasse unter den Tisch fallen lässt. Ob ich da jetzt einen zusätzlichen Faktor dazupacke oder den in die Konstante verrechne, ist ja egal. Und noch die Formel für den Radius: `r = sqrt[(x×y)/(4×pi)]`

Du bist ja unser Physiker ;-) Wenn das so OK ist, baue ich das noch in den Pull Request ein.

**Comment by CsharpLassi** [comment]
Mann könnte vielleicht auch mal die Einsteinsche Feldgleichung bemühen, um das zu Berechnen.^^

Sollte vielleicht als erste Näherung funktionieren, wenn das etwas unschön wird, kann man sich auch etwas besseres einfallen lassen.

Mach mal ein Request und das mit den Physiker beantworte ich nicht ^^

**Comment by jvbsl** [comment]
Vergesst nicht, dass es am ehesten einer donut form entspricht , also ist die Gravitation an der innenseite des donuts z.b. sehr gering :P

**Comment by CsharpLassi** [comment]
Also doch Einstein, ich freu mich drauf.


Julian willst du das machen

**Comment by jvbsl** [comment]
Jap außen wirds 42 N/kg und innen 3, dann wird mit nem cosinus interpoliert

**Comment by ManuelHu** [comment]
Ich habe das jetzt mal nach meiner Methode implementiert. Wenn sich jemand dazu berufen fühlt, das mit Einstein neu zu implementieren, dann gerne. Meins waren nur zwei Zeilen ;-)

**Comment by CsharpLassi** [comment]
vielleicht könnte man noch G und die mittlere Dichte auslagern, so das zumindes rho sich auch von Planet zu Planet ändern könnte

**Comment by ManuelHu** [comment]
Im letzten Commit habe ich die mittlere Dichte als optionalen Parameter in den Konstruktor und G als eigene `const` ausgelagert.
