### ISSUE TITLE
Client freezt

### ISSUE THREAD

**Issue by CsharpLassi** [OctoAwesome/octoawesome#221]
Der Client hängt freezt nach ein paar Sekundensimulationszeit.

Zumindest unter Linux.

**Comment by CsharpLassi** [comment]
Es liegt anscheinend an den ChunkRender beim erstellen der VertertexBuffer

**Comment by CsharpLassi** [comment]
Bei Engenious an der Stelle get_uicontext()

**Comment by CsharpLassi** [comment]
sollte mit der Engenious Version 0.1.9 gelöst sein.

**Comment by Gallimathias** [comment]
Dann einfach mal testen, wenn es weg ist kann man das issue schließen

**Comment by CsharpLassi** [comment]
Es müsste noch auf mehr Systeme getestet werden, und es ist bis jetzt nur im feature/shadow Branch vorhanden.

**Comment by CsharpLassi** [comment]
Mir ist es seit Tagen, nicht mehr Aufgefallen.
Scheint gefixt zu sein.
