### ISSUE TITLE
Playername implementieren

### ISSUE THREAD

**Issue by Gallimathias** [OctoAwesome/octoawesome#227]
Einen einstellbaren Playernamen implementieren. 

In der Player.cs

Ist vorallem im Network wichtig. Außerdem siehe hierzu verwendung bei der Serialisierung. (_OctoAwesome.Client.Components.SimulationComponent_)

**Comment by HierGibtEsDrachen** [comment]
Würde generell Name für Entities implementieren. Wir haben einen schwarzen Rahmen für Blöcke wenn mit diese interagiert werden kann. Für Entities könnte der Name darüber angezeigt werden.

**Comment by Gallimathias** [comment]
Das wäre ein eigenes Issue @HierGibtEsDrachen bitte mache entweder ein eigenes dazu auf oder mach doch mal die anderen Sachen fertig an denen du schon drann bist.

**Comment by CsharpLassi** [comment]
Dazu wäre es Sinnvoll eher eine NameComponent zu erstellen

**Comment by fnawratil** [comment]
Woher sollen die Playenamen kommen? Ein Vorschlag wäre, die Server-Abhängig zu machen.

Beim Verbinden mit einem Server kann der Nutzer einen Playername und ein Passwort angeben.
Wenn der Server den Playername schon kennt wird das Passwort überprüft, ansonsten wird einfach ein neuer Player mit der angegebenen Playername/Password Kombination erstellt.

Das wird insbesondere dann interessant, wenn wir _irgendwann_ mal ein "Rechte-System" (Admins, etc.) auf Servern haben wollen.

Eine Alternative dazu wäre ein zentraler Auth-Server der alle Spieler gegenüber den Servern authentifiziert. Das widerspricht m.M.n. aber der Idee hinter Octo.

Als dritte Option - wenns ganz fancy werden soll - könnte man auch vom Server entkoppelte Auth-Server erstellen, mit denen sich Server nach belieben verbinden können. Dann könnte man entweder einen eigenen Auth-Server für seinen Server erstellen oder sich mit anderen Servern zusammentun und _einen gemeinsamen_ Auth-Server hosten. Das vereint sozusagen die beiden Ideen von oben und würde mir persönlich am besten gefallen.

(Wenn man sich entschieden hat, was wirklich gewünscht ist, sollte das auch in eine eigene Issue - momentan steht aber wohl noch nichts mit dem PlayerName fest (oder hab ich da was verpasst), also hab ich den Vorschlag mal hier rein geschrieben).

**Comment by ManuelHu** [comment]
Also ich denke erstmal reicht es, einen Playernamen eingeben zu können und dass dieser lokal gespeichert wird (App.config - so dass man ihn nicht jedes mal neu eingeben muss). So können wir erstmal Multiplayer ausprobieren und wir können die Spieler schon mal unterscheiden.

Jede Art von Authentifizierung ist meiner Meinung nach ein anderes Issue wert und wir sollten uns jetzt auf noch nichts festlegen. Später muss natürlich irgendwie der Name mit einem Profil verknüpft werden.

**Comment by Gallimathias** [comment]
Wir haben das erst mal ganz simpel gehalten und es funktioniert
