### ISSUE TITLE
Man kann sich nicht mehr Bewegen

### ISSUE THREAD

**Issue by Gallimathias** [OctoAwesome/octoawesome#228]
Und die Gravitation ist auch futsch.

Der Fehler ist nach dem Update von Monogame UI und Engenious aufgetaucht.

**Comment by Gallimathias** [comment]
Mit Engenious 1.8 ist die Welt noch in ordnung.

**Comment by Tayukimo94** [comment]
Ich habe mir mal den aktuellen Dev-Stand von Engenious geholt und manuell ins Projekt eingebunden.  Damit geht wieder alles. Scheint irgendwas nicht mit dem Nuget-Paket zu stimmen oder ist der Dev-Stand im Engenious-Repository nicht aktuell?

**Comment by jvbsl** [comment]
ich und @Gallimathias haben uns das ganze angeschaut, hängt mit Memory-Alignment auf 64-Bit und unterschiedlicher Ausführung von .Net auf unterschiedlichen Prozessoren zusammen. Möglicherweise ein Problem in .Net selbst.

**Comment by Gallimathias** [comment]
@Tayukimo94 du hattest das problem ja auch während dem stream oder? Welchen Prozessor hast du?

**Comment by Gallimathias** [comment]
Es gibt dazu jetzt ein offizielles Issue bei .NET: https://github.com/dotnet/roslyn/issues/24233

**Comment by Tayukimo94** [comment]
Während dem Stream hatte ich das auch. Ich habe den AMD FX-6350. Wie geschrieben, habe ich den Fehler nur weg bekommen, indem ich alles manuell eingebunden habe. Der build war selbst auf "Any CPU" eingestellt, also bei mir sollte das dann x64 sein.

**Comment by Gallimathias** [comment]
Ok danke für die Info.

**Comment by Gallimathias** [comment]
Temporär gefixt mit https://github.com/OctoAwesome/engenious/commit/cc33f3c06d19b751e9e05770b711301552c83dd0
