### ISSUE TITLE
Ghost Wauzi 

### ISSUE THREAD

**Issue by Gallimathias** [OctoAwesome/octoawesome#229]
Die Wauzis sind teilweise unsichtbar. Ist das ein Gewerkschaftsstreig oder ein Bug?

**Comment by jvbsl** [comment]
fixed with https://github.com/OctoAwesome/engenious/commit/7b2de77f370daf316fd2ffb996d7c0e98230fbb4
current nuget package has this bugfix aswell -> so fixed with
https://github.com/OctoAwesome/octoawesome/tree/feature/shadow

**Comment by Gallimathias** [comment]
Ich mache das Issue erneut auf weil es in der aktuellsten Version (0.1.28) immer noch vorkommt. Mir scheinen auch manche Bäume diese auflöse erscheinung zu haben.

**Comment by jvbsl** [comment]
wtf, schmeiß dein Windows weg^^ Bzw. hast du auch die models neu gebuildet, wenn man auf die aktuelle Version wechselt muss man einen ziemlich harten rebuild machen und ich glaube sogar das ContentProjekt selbst müsste man nochmal bearbeiten und alle Importer/Processor nochmal setzen und neu abspeichern...

**Comment by Gallimathias** [comment]
Fehler taucht nicht mehr auf in den letzten streams
