### ISSUE TITLE
Confilicts in "Merge branch 'feature/code_of_conduct' into develop "

### ISSUE THREAD

**Issue by CsharpLassi** [OctoAwesome/octoawesome#231]
Hallo,

was ist den da passiert, es gibt im letzten Merge ein paar Konflikte.
Bitte dringend beheben und zu ende mergen.

https://github.com/OctoAwesome/octoawesome/commit/1217a4174a2a289155da86062e7990e2d3cc9518

**Comment by Gallimathias** [comment]
Meinst du die Conflicts die ich im Kommentar erwähnt hatte?

Das sind Line endings und die wurden gefixt ich übernehme in so einem fall nur immer das standard kommentar damit erhalten bleibt wo es probleme gab oder wo gibt es noch konflikte?.

**Comment by CsharpLassi** [comment]
Bitte keine Konflikte als Kommentare drinne behalten.
Da es nicht klar ist ob welche existieren oder nicht. Man geht davon aus das sie nicht gefixt wurden sind. Wie in diesen Fall !!

Hab nur das gelesen und dachte mir "Was soll das ??"
