### ISSUE TITLE
Frage zu Umgang mit Merge-Request

### ISSUE THREAD

**Issue by CsharpLassi** [OctoAwesome/octoawesome#235]
Hallo,

eine allgemeine Frage zu Umgang mit Merge-Request.
Da Manu wieder ein Request aufgemacht. Wie schnell oder wann sollen die gemergt werden??

Weil gerade bei den Request ist es wichtig das Develop keine Änderungen hat, damit das nicht zu übermäßigen Problemen führt.

Also mein Vorschlag kleine Dinge direkt Mergen und nur im nächsten Stream oder Video erwähnen und bei größeren Dingen, wirklich direkt im Stream oder ähnliches Mergen.

**Comment by Gallimathias** [comment]
Siehe hierzu: [Pull Request Template](https://github.com/OctoAwesome/octoawesome/blob/develop/PULL_REQUEST_TEMPLATE.md)

Grundsätzlich ist es im Code of Conduct vorgesehen das Änderungen öffentlich geschehen. Mergbar wäre ein "größerer" Pull Request also immer dann wenn ein Video/Stream/Blogeintrag etc. exestiert.

kleinere Änderungen können direkt gemergt werden. Das sind in meinen Augen alle dinge die __keine__ Logikänderung beinhalten (zmd. keine wesentlichen) oder Grundsatzentscheidungen betreffen.

Ich habe den neuen Request noch nicht angeguckt aber alleine schon vom Issue her wäre das etwas was ich nicht direkt mergen würde.

**Comment by ManuelHu** [comment]
Ich bin am Donnerstag auch wieder da, da kann ich ja kurz erklären was ich gemacht habe und dann mergen.

**Comment by Gallimathias** [comment]
Ich glaube wir haben das gut besprochen. Es gibt zwar noch Detailfragen die geklärt werden müssten das hängt aber nicht mit den Pull Request an sich zusammen. Sollte zum Thema Pull Request noch rede bedarf sein einfach das issue neu öffnen.
