### ISSUE TITLE
Position reset im dev branch

### ISSUE THREAD

**Issue by Gallimathias** [OctoAwesome/octoawesome#238]
Im develop branch werden beim laufen durch einen wald manchmal die Koordinaten des Spielers zurückgesetzt.

**Comment by ManuelHu** [comment]
Tritt dieses Problem immer noch auf?

**Comment by susch19** [comment]
Also in letzter Zeit habe ich davon nichts gesehen, weder im Stream, noch bei privater Entwicklung, also scheint das wohl inzwischen behoben :)
