### ISSUE TITLE
Doppelter MapGenerator-Parameter 

### ISSUE THREAD

**Issue by ManuelHu** [OctoAwesome/octoawesome#239]
Im `ComplexMapGenerator` wird an neue Planeten der MapGenerator sowohl an den Konstruktor als auch in den Initialisieren übergeben. Im Konstruktor wird er aber nicht verwendet/gespeichert.

https://github.com/OctoAwesome/octoawesome/blob/develop/OctoAwesome/OctoAwesome.Basics/ComplexPlanetGenerator.cs#L14

**Comment by HierGibtEsDrachen** [comment]
Das fix mal auch ... oh verdammt ich bin ja noch Wach (:

**Comment by Gallimathias** [comment]
Ich denke das man den Generator aus dem ctor entfernen kann

**Comment by ManuelHu** [comment]
Ja

**Comment by Gallimathias** [comment]
Wurde bereits umgesetzt
