### ISSUE TITLE
Client- Serverarchitektur

### ISSUE THREAD

**Issue by Gallimathias** [OctoAwesome/octoawesome#240]
Wir müssen die Client- Serverarchitektur gestalten.

dazu gehören:

* [x] einbindung der Simulation
* [x] Synchronisieren der Daten
  * [x] Mapdaten austausch -> evtl nur seeds.
  * [x] Playerposition austauschen
  * [x] Interaktionen austauschen -> Actions

**Comment by HierGibtEsDrachen** [comment]
Also ich weiß ich bin der neue, es ist dein Stream und du kannst es ja machen wie du es für richtig hältst aber hab gerade Folge 523 gesehen. Wenn ich mich noch richtig erinnere, war es so. Das Spiel besteht aus quasi vier Layern:

**Octoawsome.dll** war die Library für alles. Da ist und muss alles rein, dass in irgend einer weiße von höheren Softwarelayer gebraucht wird sodass dritte eigene Extension schreiben können.

Zum Beispiel von der **Basiscs.dll** die ursprünglich als Extension gedacht war und noch immer ist? Sie sollte von nichts Referenziert werden, sondern von der Runtime dynamisch geladen werden.

Die **Client.Exe** ist das Frontend, sie Renderd eigentlich nur und nimmt Spieler Inputs entgegen und kommuniziert mit dem Server.

**Die Runtime.dll** ist der Server das Backend. Jetzt fragst du dich bestimmt warum dann der Client eine Referenz auf die Runtime hat? Es war so gedacht, dass das Spiel auch ohne Internet bzw. Local spielbar ist somit muss das Game einen eigenen Server zu Verfügung stellen, allerdings muss der Client dann mit dem Server nicht wirklich kommunizieren bzw. muss es nicht über Sockets gehen und kann daher vereinfacht werde. 

Wenn ich du wäre würde ich in der Runtime weiter schreiben und die Network.dll als Library für die Kommunikation usw. verwenden. Ich würde es ganz gerne sehen wie die Off- und Online Variante so abstrahiert wird das die Client.exe also das Game (um genauer zu sein die OctoGame.cs) nicht weiß woher die Daten stammen.

Darf ich noch anmerken, dass sämtliche Positionen von allen Entities ausgetauscht werden müssen. Sowie ein Handschacke mit dem Server stattfinden sollte sodass immer nur ein User einen Block abbauen darf.

**Comment by Gallimathias** [comment]
@HierGibtEsDrachen das hast du richtig festgestellt. Was möchtest uns damit sagen? An sich wird das exakt so gehandhabt und wurde so auch geplant ^^

**Comment by HierGibtEsDrachen** [comment]
Basisklasse für Simulation: 
**RemoteSimulation**: Die in den Client injiziert wird. Diese erhält ihre Updates über einen Server. Requests usw. laufen auch über sie aber über die selben Methoden wie bei einer lokalen Simulation. 
Das gegenstück auf dem Server würde richtig Simuliert werden und dann die Daten "einfach" Pushen.
**LocalSimulation**: Wird halt lokal Simuliert, also wie jetzt. 
Was meinst? Wenn ihr das schon so macht hab ich nichts gesagt... :P

**Comment by ManuelHu** [comment]
Also derzeit nicht, nein. Wir arbeiten (noch) eine Ebene drunter: Der ResourceManager bekommt einen eigenen NetworkPersistenceManager der die Kommunikation mit dem Server aufnimmt. Die Chunks / Updates bekommt man dadurch recht gut hin. Ich sehe auch nicht, warum du auf Simualationsebene eingreifen willst. Auf Grund der schlechten Erfahrung mit der letzten Architektur soll auch lokal eine volle Simulation laufen.

**Comment by HierGibtEsDrachen** [comment]
Ok ja das das liest man so nicht raus :/ 
Auf Simulationsebene würde ich für die Entitys arbeiten. Das ist ja eigentlich das einzige, dass wirklich Simuliert wird. Die Blöcke gibt es halt., deswegen sehe ich sie nicht als Simulation.

**Comment by ManuelHu** [comment]
In der letzten Multiplayer-Implementierung wurde nur serverseitig simuliert. (Eingaben an den Server gemeldet, Server schickt Bewegung zurück - "Entities" hatten wir noch nicht). Das war performancemäßig katastrophal. Der Server sollte zwar alle Dinge die passieren, auf Plausibilität prüfen, aber die Clients haben lokal eine volle Simulation laufen

Auch entities werden ich Chunks gespeichert, könnten also über diese an den Client gepusht werden.

Allgemein fehlt uns auch mit den PersistenceManagern die Möglichkeit vom Server einen Push durchzuführen. Kommt Zeit kommt Lösung.

**Comment by HierGibtEsDrachen** [comment]
> Allgemein fehlt uns auch mit den PersistenceManagern die Möglichkeit vom Server einen Push durchzuführen. Kommt Zeit kommt Lösung.

Geht das ein bisschen genauer?

**Comment by ManuelHu** [comment]
Mit der bisherigen Idee kann der Xlient wunderbar Chunks vom Server laden - dem Server fehlt aber noch die Möglichkeit dem Client geänderte Daten zu senden über den gleichen Weg. Dürfte aber keine allzu große Änderung sein das einzubauen.

**Comment by HierGibtEsDrachen** [comment]
Wenn ihr einen Handshake macht: 
Spieler will einen Block abbauen -> beim Server den Blockreservieren und abbauen, dann sollte die Änderung im Server sein. Anschließend kann der Server alle Spieler die sich im Chunk aufhalten oder ihn geladen haben, darüber informieren?

**Comment by ManuelHu** [comment]
Jap so war der Plan. Es wird nur nicht nur mit dem Ersetzen des PersistenceManagers vollständig funktionieren. Aber so wollen wir es bauen.

**Comment by susch19** [comment]
Nicht ganz. Der User wird den Block abbauen können (lokal) und fragt im Zuge dessen, ob er es wirklich durfte beim Server. Wenn ja, dann wird der Block zu seinem Inventar hinzugefügt, wenn er es nicht durfte, dann taucht der Block wieder auf (Beziehungsweise der Chunk wird resettet). Dadurch verlangsamen wir das Mining nicht. 

Müssen dann nur schauen, was wir mit eventuellen Bewegungen machen, die in der Zwischenzeit ausgeführt werden. Meine Idee wäre den Block durch einen unsichtbaren Collidingblock zu ersetzten, dadurch kann der User niemals in einen abgebauten und wieder aufploppenden Block stehen. Diese Collidingblöcke dürften aber nur im Multiplayer platziert werden, weil es in einer reinen lokalen Simulation wenig Sinn ergibt, da wir hier nicht mit der Latency zu kämpfen haben. Die Collidingblöcke können dann entfernt werden, sobald das Okay vom Server kommt.
Die einzige Frage die ich mir stelle ist, ob man durch die Collidingblöcke hindurch graben können soll (Also Bewegung blockieren, aber das Mining nicht, ansonsten wäre das Mining genau so blockiert, wie oben auch, nur sähe es visuell besser aus)

**Comment by HierGibtEsDrachen** [comment]
Die Chunk resets und unsichtbare Kollisionsblöcke gefallen mir eher weniger. Als 0.5 Sekunden pro Block zu werten, also wenn das nicht drin ist. Wenn schnell ist den die billige Kopie von Octo?^^

**Comment by Gallimathias** [comment]
Die Idee mit den unsichtbaren Blöcken könnte man in betracht ziehen, würde ich aber aktuell nicht forcieren sondern eher erst dann aus der Schublade holen wenn es anders nicht geht.

Aktuell bin ich auch weiterhin für den simplen Reset und das macht auch die billige Kopie so ^^. Die Überprüfung auf der Client-Seite macht nur bedingt sinn. Natürlich muss diese auch Überprüfungen implementiert haben aber man kann und soll sich nicht auf den Client verlassen. Die Verantwortung liegt beim Server.

Außerdem erzwingt eine Client-Seitige Überprüfung nach aktuellem stand ein Ping-Pong-Prozedere mit dem Server, was ich gerne vermeiden würde und lieber das "Resultat" übermittle. 

Der Reset der Blöcke ergibt sich quasi von selbst, durch das Update, ohne explizit etwas zurückzusetzen. Da der Server nach aktueller Planung einfach ungültige Aktionen verwirft.

**Comment by reicheltp** [comment]
Hier auch mal etwas Input von mir: ( Lese immer nur in GitHub, daher sorry, falls das schon im Stream angesprochen wurde. ;) )

Eventuell kann man sich ja auch an der Network Protocol Implementierung von Minecraft Orientieren: http://wiki.vg/Protocol

Allgemein schickt der Client in regelmäßigen Abständen seine neue Position und Blickrichtung. (ca alle 50ms) Hier führt der Server lediglich eine Plausibilitätsprüfung durch, um so etwas wie Clientseitige Speed Hacks zu verhindern. Ansonsten werden auf Position Updates nicht geantwortet. (TCP stellt ja bereits sicher, dass der Server die Nachricht wirklich erhalten hat).

Sämtliche Interactionen mit der Welt werden jedoch vom Server bestätigt.
Beispiel Block abbauen (siehe http://wiki.vg/How_to_Write_a_Client#Digging):
 - Client schickt Starte Abbauen
 - Server sendet Block Update, wenn der Block tatsächlich abgebaut ist. Und spawned die abgebauten Items an Stelle x
 - ODER Client schickt Beende Abbauen und alles bleibt, wie es ist.

**Comment by Gallimathias** [comment]
Ich gucke es mir mal an ^^. Allerdings muss man ja mal sagen das Minecraft nicht gerade der Inbegriff von Performance und Stabilität ist XD

**Comment by CsharpLassi** [comment]
Ich will oder muss wohl auch noch mein Senf dazu geben, damit es erst recht voll wird.

Also ich bin mir nicht sicher ob Hacking in irgendeine Rolle interessant für uns ist. Es geht ja maximal darum zu erkennen ob irgendwas nicht stimmt was der Spieler macht und dann einzugreifen.

Dieses den Spieler ständig und immer zu Überwachen ist glaub ich der falsche Weg und auch nicht Notwendig. Anders sieht es wahrscheinlich bei Spielen wie (keine Ahnung die AAA mit Rankingmultiplayer aus oder so).

Deshalb finde ich Performance wichtiger, als den Spieler zu "überwachen". Ich denke es ist besser das der Spieler sagt, was er macht und wir ihn nur unterbrechen, wenn was nicht stimmt.

**Comment by Gallimathias** [comment]
Erst mal simpel implementiert und funktioniert erst mal mit einem Notification-System. Weitere Implementierungen aka Spielerüberwachung und Performance Verbesserungen erfolgen in einem anderen Issue und später
