### ISSUE TITLE
Alienraumschiffstrukturen, warsch Renderfehler

### ISSUE THREAD

**Issue by Gallimathias** [OctoAwesome/octoawesome#242]
Wir haben scheinbar Aliens die Hin und wieder Spawnen. Ich würde mal sagen das hier an der Falschen stelle gerendert wird die Blöcke sind nämlich nicht da.

![octobug](https://user-images.githubusercontent.com/16351673/36568293-bcde32fc-1829-11e8-9c93-d2ab51b7f531.JPG)

**Comment by CsharpLassi** [comment]
Ich würde sagen es ist kein Renderfehler indem Sinn, sondern mehr ein Problem mit den Chunkrenderer. Aber wie immer alles ist Möglich.

**Comment by susch19** [comment]
Das wurde zwischenzeitlich bereits gefixt. Da wurden ChunkRenderer verarbeitet und dann wurde bei der Verarbeitung die Position neu gesetzt, aber der ChunkRenderer nicht neu gerendert, da der Loaded Flag am Ende gesetzt wurde.
Nun ist eine Prüfung drin am Ende, ob die Position noch die gleiche ist, wie am Anfang und wenn nicht, dann wird er neu generiert.
