### ISSUE TITLE
Grundlegende Refaktorisierung 

### ISSUE THREAD

**Issue by HierGibtEsDrachen** [OctoAwesome/octoawesome#243]
Der MapPopulator sollte die eine Entity in die Simulation injizieren und von dort aus sollte sie ihren weg zur ChunkColumn finden, würde einem Server - Client Konzept entgegen kommen. 

Braucht eine Extension Entity wirklich den ResourceManager, denn dieser kann ein neues Universum erzeugen. Es nicht so das ich Wauzi nicht traue, aber das ist ein bisschen zu viel Macht in den Händen eines Hundes ohne KI ^^
An Wauzi bin ich aber schon durch #241  dran.

**Comment by ManuelHu** [comment]
Eine Extension-Entity braucht den ResourceManager nicht vollständig. Der GlobalChunkCache, die GetPlanet / GetUniverse / CurrentUniverse / DefinitionManager werden aber ggf. (bei Wauzi nicht) gebraucht.

Populators können Entities nur beim neuen Erzeugen der Chunks anlegen, diese gehören dann quasi zu den Initialdaten. Da sehe ich keinen Handlungsbedarf, da nur der Server die Mapdaten generiert. Später hinzugefügte Entities (z.B. mit Spawneggs) müssen natürlich über die Simulation hinzugefügt werden und ggf. an den Server gemeldet werden.

**Comment by HierGibtEsDrachen** [comment]
Ja ok. aber eine Entity ist ein Bestandteil der Simulation und nicht ein Bestandteil eines Chunks. Die Entity hält sich höchstens dort auf. Zur zeit werden sie beim erzeugen des Columns in dei Column Entitylist injiziert. Und durch Simulation.BeforeUpdate() in die Simulation auf eine Warteliste gesetzt werden und dann im ChunkColumn platziert.

**Comment by ManuelHu** [comment]
So halb. Eine Entity ist nur so lange in der Simulation wie der Chunk im Sichtbereich steht. Danach wird diese mit dem Chunk weggespeichert. Es braucht also auch eine Möglichkeit aus Chunks heraus Entities "wiederzubeleben", egal ob in frisch generierten oder "alten" Chunks. Genau das ist der von dir bemängelte Mechanismus.

**Comment by HierGibtEsDrachen** [comment]
Interfaces für Klassen die in der selben dll liegen entfernen oder Klassen verschieben.
IGlobalChunkCache - GlobalChunkCache

**Comment by Gallimathias** [comment]
Bitte mache nicht solche massen Issues @HierGibtEsDrachen. Dein kommentar scheint mir ein eigenes Issue zu sein. Auf deine Eingehende Frage hast du bereits durch @ManuelHu eine Antwort bekommen.

**Comment by CsharpLassi** [comment]
Naja ich denke wir haben zurzeit ein paar andere Schwerpunkte, als überflüssige Interfaces.

Wichtiger sind da bestimmt die Punkte im Projekt Simulation Redesign, auch wenn die Liste bis jetzt noch nicht vollständig ist.

Hinweis noch an der Stelle, wenn Änderungen gemacht werden (als Pull-Request), bitte ihn kleine und Handlichen Portionen und nicht alles auf einmal.

Damit schließe ich das jetzt, bringt an der Stelle kein Mehrwert mehr.
