### ISSUE TITLE
System.NullReferenceException im RenderControl (YT_Folge 3)

### ISSUE THREAD

**Issue by gizmo2101** [OctoAwesome/octoawesome#255]
Hallo zusammen 
Ich stell mich mal kurz vor 
Ich bin christian und ein neuling in sachen programmieren 
Ich versuche scchon seit längerem OctoAwesom nach zu programmieren
wo ich immer mal viele fehler machen und es dan dazu kommt das ich alles nochmal von vorne anfangen muss. 

Jetzt aber hatte  ich mir fest vorgenommen mehr elan ins programmieren reinzustecken und hartnäckig zu bleiben was ich jetzt auch schon seit 3 gut klappt, denn ich stecke seit dem bis folge 4 auf youtube fest.  Weil ich ständig probleme bekomme entweder duch einer exception oder weil mein englisch nicht sehr toll ist und ich so nicht viel hilfe in anspruch nehmen kann.

Meine probleme lagen darin das ich bei einer Nullreference exception stecken geblieben bin.
habe vs 2013, 2015, und 2017 auf Win 8 benutzt und das einzigste wo der Code von folge 1-4 vernünftig funktioniert war vs 2013. mit  vs 2015 u 2017 gab es ständig probleme. entweder eine exception oder alles wurde ohne fehler ausgeführt aber nicht war  zusehen.

und jetzt eine neue entdeckung  habe jetzt win 10 mit vs 2017 klappt alles wunderbar, selbst ohne abfrage ob Game gesetzt ist mit if ( game == null) return;

**Comment by Gallimathias** [comment]
Original konversation auf [Youtube](https://www.youtube.com/watch?v=ksqAh9ol8yk&t=968s)

Hallo Chrisitan schön das du hierher gefunden hast. Wie ich dir bereits geschrieben habe kann die System.NullReferenceException nicht mit der Visual Studio Version oder dem Betriebssystem zusammenhängen.

Du hast ja auf YT geschrieben das der genaue Fehler lautet: System.NullReferenceException: "Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt."

Das deutet darauf hin das an dieser Stelle das Game nicht analysiert wurde.

Wir probieren mal folgendes, kannst du mal dein komplettes Projekt (also der Ordner mit der .sln Datei darinn) in eine zip Datei packen und hier an ein Kommentar dranhängen. (einfach die Datei in das Kommentar das du verfasst reinziehen). Dann gucken wir uns mal an was da passiert. :)

**Comment by gizmo2101** [comment]
Ich hab die Datei nicht mehr 
ich benutze ja jetzt Vs 2017 und win 10  und da läuft es bisher.

**Comment by Gallimathias** [comment]
Hast du alles gelöscht und noch mal neu nachprogrammiert?

**Comment by gizmo2101** [comment]
Ich mußte mein Win 10 2 mal neu booten und habe leider die sachen nicht auf eine externe platte gepackt
aber bei den nächsten fehlern komm ich drauf zurück

**Comment by gizmo2101** [comment]
[Neuer ZIP-komprimierter Ordner.zip](https://github.com/OctoAwesome/octoawesome/files/2367019/Neuer.ZIP-komprimierter.Ordner.zip)

**Comment by Gallimathias** [comment]
Da du jedes mal die Sache neuprogrammiert hast, hast du eventuell ein Fehler in den nicht funktionierenden Varianten gemacht.

Die stelle an der das If steht klappt deshalb da die Zuweisung des Games in die Eigenschaft des RenderControls __vor__ dem ersten Aufruf der Paint methode passiert.  Da du das aber auf diese weise nicht ganz garantieren kannst ist es deutlich besser und richtiger in der Paint methode durch das if die Situation abzufangen wenn das Game null entspricht also nichts da ist.

**Comment by gizmo2101** [comment]
Hey Neue problem bin jetzt soweit das ich sprite animiere 
und bin einfach mal auf form 1 cs entwurf gegangen und bekomme direkt fehler angezeigt

1. wegen meinem bild im asset ordner 
da kommt das herraus::: 
1. |   | Aufrufliste ausblenden
bei System.Drawing.Image.FromFile(String filename,  Boolean useEmbeddedColorManagement)bei System.Drawing.Image.FromFile(String  filename)bei Farbe_im_Fenster.RenderControl..ctor() in  D:\Programmieren\Farbe im Fenster\Farbe im Fenster\RenderControl.cs:Zeile 30

und fehler 2 hat was mit dem Designer zu tun 


Die Variable  renderControl wurde nicht deklariert oder nicht zugeordnet.    

1.   Farbe im Fenster  Form1.Designer.cs Zeile: 56 Spalte: 1 

und das ist ein auszug aus dem Designer  zeile 53 bis 62

this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Controls.Add(this.renderControl);
            this.KeyPreview = true;
            this.Name = "Form1";
            this.Text = "Form1";
            this.ResumeLayout(false);

        }

      
[Neuer ZIP-komprimierter Ordner.zip](https://github.com/OctoAwesome/octoawesome/files/2368497/Neuer.ZIP-komprimierter.Ordner.zip)

**Comment by Gallimathias** [comment]
Problem wurde mit letztem Kommentar gelöst. Wenn nicht und das selbe noch einmal auftaucht bitte neu öffnen oder neues Issue aufmachen
