### ISSUE TITLE
FilenotFoundException  

### ISSUE THREAD

**Issue by gizmo2101** [OctoAwesome/octoawesome#257]
Hallo Ich weiss kann nervig sein aber ich habe das problem FilenotFoundException  

kurz gesagt  wenn alle datein vorhanden sind wie kann vs mir sagen das ich eine FilenotFoundException  habe 
die png sind überall zu finden im Debug  ordner und sogar im Release ordner

**Comment by Gallimathias** [comment]
Es wäre wieder ganz gut wenn du uns deinen Projektordner anhängen könntest. Dann kann man gucken wo das Problem genau liegt :).

**Comment by gizmo2101** [comment]
[Neuer ZIP-komprimierter Ordner.zip](https://github.com/OctoAwesome/octoawesome/files/2375757/Neuer.ZIP-komprimierter.Ordner.zip)

**Comment by gizmo2101** [comment]
ich hab bis folge 8 alles fertig bekommen nur er rendert mir die png´s nicht

**Comment by jvbsl** [comment]
ich fänds famous wenn ihr das auf ein gesondertes Repository legen könntet. Einerseits sorgt das dafür, dass man den Code direkt online überprüfen kann und direkt zu Codezeilen kommentieren kann. Andererseits ist es nicht direkt hier bei OctoAwesome, womit es direkt - so find ich - nicht mehr so viel zu tun hat.

**Comment by Gallimathias** [comment]
Es ist OctoAwesome und er braucht hilfe, es ist hier absolut und volkommen richtig. Anfänger hin oder her wir weisen niemanden ab @jvbsl

**Comment by Gallimathias** [comment]
Das Problem ist das dein Rendercontrol zwar vorhanden ist aber nicht deiner MainForm hinzugefügt wurde. An sich kannst du das Problem lösen indem du die Rendercontrol einfach neu zur MainForm hinzufügst und das aktuell vorhandene Control entfernst.

Ich möchte aber dazu noch anmerken das das aktuell nicht klappen wird da du den Fehler aus deinem Issue #256 immer noch nicht gefixt hast. Die Lösung hatte ich dir hierzu ja bereits im anderen issue genannt.

_Nach dem du dein RenderControl repariert hast_
Zum entfernen des bereits vorhandenen RenderControls:

1. gehe in MainForm.cs
2. gehe mit dem Cursor auf ````InitializeComponent()````
3. Drücke F12
4. Entferne dor alles was mit ````this.renderControl_1```` anfängt

P.s. du kannst ruhig weiter Tickets aufmachen wie bisher, das ist vollkommen richtig so :)

**Comment by jvbsl** [comment]
@gizmo2101 ich glaube da habt ihr mich beide etwas missverstanden. Es hat absolut nicht damit zu tun ob du Anfänger bist oder nicht. Es ging mir eher um die kategorische Einordnung, welche imho halt hier nicht passend ist, und @Gallimathias scheint das auch anders zu sehen als ich. Wir haben bereits darüber diskuttiert und sind zu dem Schluss gekommen, dass entweder @CsharpLassi ein Forum schreibt und wartet, oder ein neues Label für die Issues hinzugefügt wird.

Außerdem hatte ich ja noch Vorteile genannt von nem extra Repo, denn dann hätte ich auch gegebenenfalls geholfen, aber da ich nunmal Faulheit in Person bin ist es mir zu viel Aufwand eine Zip herunterzuladen :P

**Comment by gizmo2101** [comment]
Ich versteh dich ja auch,
Ich weiß auch als das project angefangen ist auch ne menge zeit vergangen ich glaube sind schon 4 jahre 
aber was soll jemand machen der so wie ich gerade damit anfäng und dieses Project versucht nach zu coden,
und so wie ich ständig probleme bekommt mit den ide´s.
dazu muss ich sagen es ist glaub ich schon mein 20 project und einige stunden wo ich versuche weiter zu kommen mit OctoAwesome und immer wieder niederschläge bekomme.
