### ISSUE TITLE
Neuer Shader macht Probleme auf OpenGL

### ISSUE THREAD

**Issue by tomwendel** [OctoAwesome/octoawesome#26]
getestet und verifiziert auf Linux und WindowsGL

- notwendiger Wechsel von PS_4_0 auf PS_3_0
- Parameter-Namen werden falsch übersetzt
- mysteriöser Compiler Fehler beim Draw-Call

**Comment by ManuelHu** [comment]
Ist das jetzt mit dem Wechsel auf Engenious nicht überflüssig?

**Comment by tomwendel** [comment]
stimmt
