### ISSUE TITLE
Blockierung des Actor Updates sollte auf die Reichweite der Physik beschränkt sein

### ISSUE THREAD

**Issue by tomwendel** [OctoAwesome/octoawesome#48]
Die aktuelle Lösung ist schnell und bequem. Da der Local Chunk Cache ja eh nur die unmittelbar in der Nähe liegenden Chunks lädt sind die meisten davon eh für die Physik relevant. Wenn ich mich beim Block aber wirklich nur auf die unmittelbar betroffenen Blocks kümmern will wirds kompliziert. Ich kann

a) die Berechnung in dem Augenblick unterbrechen, wenn die Kollisionsprüfung bemerkt, dass der Chunk nicht da ist. Das würde aber die komplette Update-Domain in Mitleidenschaft ziehen.
b) vor jedem Update des ActorHosts die Range der Physik nutzen um die betroffenen Chunks zu checken. Das wäre eine Option die wir für die Netzwerk-Funktionalität vielleicht nutzen könnten.

Eine weitere Option wäre vielleicht
c) der Actor-Host lädt nicht nur einen zusätzlichen Chunk in alle Richtungen (also immer 27) sondern einen Schritt weiter (das wären dann schon 125), blockiert aber nur, wenn die inneren 27 nicht da sind). Das würde dem Ladeprozess einen Chunk Vorsprung geben, vervierfacht aber im Worstcase den Speicherbedarf eines einzelnen Actors beim Server-Betrieb.

**Comment by CsharpLassi** [comment]
Ich denke man könnte einiges raus holen was das laden der Chunks für den Actorhost angeht. 
Wir können eigentlich relativ genau sagen wann und wo sich ein Spieler befindet, wenn alles mit rechten Dingen zugeht. Das würde ja dem Punkt b enstprechen. 
Auf dem Server kann es aber dann ja noch einfacher werden, weil der Server muss oder soll ja keine Bewegungen berechnen. 
Der Client macht weiterhin Kollisionsberechnung und und und. Das ganze wird zum Server geschickt und dieser bestätigt nur die Aktion. Dadurch reicht eine einfache Plausibilitätsüberprüfung anhand alter Werte.  Ein Vorhalten von Chunks im Server für den Aktorhost würd sich dann auf nur wenige belaufen, eventuell auch keine.

**Comment by tomwendel** [comment]
Ich fürchte um die Bewegungsberechnung am Server kommen wir nicht rum. Zwar könnte jeder einzelne Player seine Berechnungen für sich machen, aber es gibt ja auch noch autonome Spiel-Einheiten (Tiere, NPCs, Bots,...). Diese müssen alle auf dem Server berechnet werden - da kommt es auf die paar Spieler auch nicht mehr an. Außerdem könnte sich eine Plausibilitätsprüfung durchaus als kompliziert erweisen, da es ja dank Delay zu vollkommen unterschiedlichen Situationen kommen kann (Client hat den Block schon entfernt, beim Server ist er noch da)

Meine aktuelle Strategie sieht vor, dass wir die Simulation parallel auf Server und Client laufen lassen. Bei unterschiedlichen Ergebnissen hat aber der Server immer Recht. Ich könnte mir vorstellen, dass das vom Chunk-Aufkommen (serverseitig) her auch nicht wesentlich umfangreicher ist als der Ansatz mit der Plausibilitätsprüfung. Auch da brauche ich ja die selben Chunks wie der Client für die Kollision.

**Comment by CsharpLassi** [comment]
Autonome Einheiten geh ich mit die kommen vom Server. 
Bei nicht NPC-Eiheiten müsstes du aber jeden Input mit nehmen der auf dem Client getätigt wird und das glaub ich lohnt sich nicht bzw wird auch so nicht möglich sein. 

Die Delay sind ja auch typische Minecraftprobleme und da tauchen auch auf einmal wieder Blöcke auf.  Das der Server immer recht ist ja gut und Richtig, aber nicht jede Differenz muss zu einem "Reset" der Klienten führen. Da ist die Bewegung ein Kriterium was ich deutlich schwächer Bewerten würde, wenn es nicht zu Positionen Änderungen kommen die nicht möglich sind.
Nochmal zu Minecraft das muss ja nicht sein das Blöcke wider auftauchen ^^.

Wir bedenken ja auch viele Dinge noch nicht, die noch dazukommen werden wie Updates von Blöcken, Baumwachstum oder Maschinen. Da denk ich werden wir doch große Probleme bekommen was Rechenzeit angeht.

Aber erstmal muss ein Server stehen oder willste schon mal Anregungen für den Server sammeln ^^

**Comment by Gallimathias** [comment]
Ist das noch aktuell @CsharpLassi @tomwendel

**Comment by CsharpLassi** [comment]
Puuh, ist nicht mehr aktuell, weil es ja in der Form die Implementierung nicht mehr gibt. Für Multiplayer muss aber das Problem noch mal richtig angepackt werden. Da es aber nichts sinnvolles enthält was nützlich sein könnte. 

Close
