### ISSUE TITLE
Kollision geht nicht

### ISSUE THREAD

**Issue by CsharpLassi** [OctoAwesome/octoawesome#52]
Hallo,

die Kollision funktioniert nicht, wenn man Vorwärts und Seitwärts gleichzeitig geht.
Man kann so durch Blöcke durch gehen. 
Hab das ganze unter Linux getestet , bitte mal unter Windows überprüfen.

viele grüße
Lassi

**Comment by ManuelHu** [comment]
Ich konnte den Fehler mal so auf die Schnelle nicht reproduzieren (Windows).

**Comment by tomwendel** [comment]
Kann ich "leider" auch nicht nachvollziehen. Aber ich hatte schon mal in irgend einem unserer Streams das Phänomen, dass man mit ein paar Versuchen in die Wand glitschen konnte. Ich tippe auch Parallelen. Eine Ursachen-Idee habe ich aber nicht :(

**Comment by CsharpLassi** [comment]
Stimmt unter Windows geht es. Ich schau mir das mal genauer an

**Comment by CsharpLassi** [comment]
Konnte den Fehler in Octoawesome auch nicht unter Linux mehr herstellen, als ich alle aktuelle Commits eingefügt habe. Eventuell haben wir den schon gefixt

**Comment by tomwendel** [comment]
Mhhh. Wir haben in diesem Zusammenhang aber meines Wissens nichts gemacht.

**Comment by ManuelHu** [comment]
Ich schließe das hier mal. Wenn der Fehler wieder auftritt und auch reproduzierbar ist, könnt ihr es wieder öffnen.
