### ISSUE TITLE
Linux Mono

### ISSUE THREAD

**Issue by boonkerz** [OctoAwesome/octoawesome#91]
Hallo,

Ich bekomme hier beim Kompilieren in Monodevelop einen Fehler.
Error: /media/thomas/Daten/octoawesome/OctoAwesome/OctoAwesome.Client/OctoAwesome.Client.csproj: /media/thomas/Daten/octoawesome/OctoAwesome/OctoAwesome.Client/OctoAwesome.Client.csproj could not import "$(MSBuildExtensionsPath)\MonoGame\v3.0\MonoGame.Content.Builder.targets" (OctoAwesome.Client)

**Comment by jvbsl** [comment]
Leider funktioniert die Installation von MonoGame nicht überall wie es soll(keine Ahnung warum).
Es sollte funktionieren indem du diesen Ordner erstellst: /usr/lib/mono/xbuild/MonoGame/v3.0
und diese Datei dort hin kopierst: https://github.com/mono/MonoGame/blob/master/MonoGame.Framework.Content.Pipeline/MonoGame.Content.Builder.targets

**Comment by boonkerz** [comment]
Danke ich komme weiter :)

Error: /media/thomas/Daten/octoawesome/OctoAwesome/OctoAwesome.Client/OctoAwesome.Client.csproj: /usr/lib/mono/xbuild/MonoGame/v3.0/MonoGame.Content.Builder.targets: Project file could not be imported, it was being imported by /media/thomas/Daten/octoawesome/OctoAwesome/OctoAwesome.Client/OctoAwesome.Client.csproj: '>' is an unexpected token. The expected token is '='. Line 50, position 71. (OctoAwesome.Client)

Ich kann in der XML keine Fehler finden merkwürdig

**Comment by jvbsl** [comment]
welchen Branch hast du denn geklont?

**Comment by boonkerz** [comment]
Master ich dachte das wäre der lauffähigste von allen.

**Comment by jvbsl** [comment]
der lauffähigste auf Windows ;)
Der rendering-Branch sollte Plattformunabhängig sein, ist jedoch auf einem relativ alten Stand. Außerdem wurden ein paar Tricks angewendet um das ganze zum laufen zu bekommen, da die Shader leider mit MonoGame Probleme gemacht haben(HLSL->GLSL Converter hat müll erzeugt).
Aktuell steht zur Debatte ob MonoGame nicht ausgetauscht wird(auch aus anderen Gründen)

**Comment by boonkerz** [comment]
Habt ihr schon eine Idee gegen was ihr das tauschen wollt?

**Comment by jvbsl** [comment]
https://trello.com/b/zFi2sLbb/octoawesome-staffel-2
OpenTK und selber Implementieren war dabei die Idee, daran arbeite ich auch bereits etwas. Am schönsten natürlich wenn man das dann später durch Vulkan austauschen könnte

**Comment by boonkerz** [comment]
Ich dachte Monogame wäre genau dafür. 

OpenTK sieht aber auch so ein bisschen eingeschlafen aus oder täuscht das?

**Comment by jvbsl** [comment]
OpenTK ist einfach nur ein OpenGL Wrapper und unterstütz das aktuelle OpenGL, d.h. wir können alle aktuellen Grafikkartenfeatures verwenden, MonoGame kann weder Tesselation noch GeometryShader von Compute braucht man gar nicht anzufangen.
Und die OpenGL Implementierung von MonoGame lässt an manchen stellen sehr zu wünschen übrig.

**Comment by ArcadeTactical** [comment]
Servus vielleicht wäre ja Xenko von Paradox genau die alternative die wir suchen. 
[http://xenko.com/](url) 
Hier noch ein Closer look Video [https://www.youtube.com/watch?v=hmPrUuQQz8M&list=PLS9MbmO_ssyBLHw7rZeGmriUkRaxBp7LL&index=1](url)

Scheint eine mächtige API, die mit beiden Systemen (OpenGL, D3D11+) klar kommt.
Man kann komplett  in VS arbeiten. Und verfügt über einen  Content  importer der auf Assimp basiert

Greets OldHavanaClub

**Comment by jvbsl** [comment]
Es steht bei unterstützten OS nichts von Linux/Mac, was ja eines der Hauptziele des vorhabens ist. Sie haben anscheinend eine eigene shader language, die übersetzt wird  - etwas ähnliches macht uns ja bei MonoGame Probleme. 
Ob es alles unterstützt was wir eventuell brauchen kann man leider auch noch nicht wissen

**Comment by boonkerz** [comment]
könntest du einen branch evtl anlegen mit deinen tests für opentk?

**Comment by jvbsl** [comment]
Aktuell ist es nur eine Engine, die nicht mit OctoAwesome in Verbindung steht. Mein erstes Ziel ist es diese soweit vorran zu treiben, damit MonoGameUI darauf portiert werden kann, dann kann ich dafür auch gerne ein github Projekt anlegen. 
Aktuell fehlt noch dein gescheiter SpriteBatch shader+text rendering

**Comment by ManuelHu** [comment]
Ich schließe das mal, weil wir das jetzt ja mit engenoius angehen.
