### ISSUE TITLE
High-DPI Scaling deaktivieren

### ISSUE THREAD

**Issue by fnawratil** [OctoAwesome/octoawesome#96]
Ich hab mich heute mal mit dem Verändern der Auflösung usw. gespielt und dabei eine interessante Entdeckung gemacht:

Wenn ich auf meinem Surface mit 2736x1824 pixeln Octoawesome öffne wird es nach oben skaliert.
Dies geht gut solange die Auflösung 1080 * 1920 ist, wird sie jedoch erhöht sind die Hitboxen der Controls von MonogameUI nicht mehr über den Texturen.

Dieser Fehler liegt NICHT an MonogameUI, da sich das Sample Project in MonogameUI ohne Scaling starten lässt und hier keine Probleme auftreten.

Daher meine Frage: Lässt sich das Scaling von OctoAwesome im Code deaktivieren, bzw. warum tritt der Effekt beim Sample Project nicht auf?

**Comment by ManuelHu** [comment]
Tritt der Fehler immer noch auf?

**Comment by fnawratil** [comment]
Nein...
